### ISSUE TITLE
One time use self registration links

### ISSUE THREAD

**Issue by frameset** [gotson/komga#101]
It would be neat to be able to give my friends a one time use registration link so they can set up their own account without me having to enter a username and password.

Instead, komga could allow admin account to generate a one time use link that could be shared. On the landing page the user could enter their own email and password.

**Comment by gotson** [comment]
I had this idea, that's why the usernames are email addresses already. Spring has all that's needed to configure and use an email server also.

I would need to figure out how to expire invites after a number of days. 

Few possible solutions though :
- invite an email, komga sends an email directly with a link, and the user cannot change the email
- generate a link, admin has to send the email of other mean of communication himself, and user can register with any valid mail
- mixed option: invite link is generated, option to email it directly to a user for convenience, user can choose his email

Any feedback on those options?

**Comment by frameset** [comment]
I'm happy with any of them. I suppose the flexibility of the third option is nice.

**Comment by gotson** [comment]
I like the third one better also 😊
