### ISSUE TITLE
REST API sort order not alphabetic by default

### ISSUE THREAD

**Issue by ChrisFhey** [gotson/komga#1021]
### Steps to reproduce

1. Open an app that uses the REST api (e.g.: Klutter, Paperback)
2. Open a library of choice
3. Verify that sorting is not alphabetical

### Expected behavior

Comics are sorted alphabetically by name by default

### Actual behavior

Comics are sorted by date added

### Komga version

0.157.5

### Operating system

iPad OS 16.1.1

### Other details

Komga instance is hosted using Docker.
Behaviour of apps tested on both Android and iPad OS.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by hgourvest** [comment]
Alphabetical sorting costs time because the application cannot use an index for it in the database for some technical reason. I believe that is why this default behavior was removed. Connected app developers should use the api to specify the sorting key explicitly. I think you should report this bug to them.

**Comment by gotson** [comment]
Exactly what @hgourvest said, there's no point to default to a costly sort when sort params are available.
