### ISSUE TITLE
add support for 3rd party sources like netsky's to read directly from komga

### ISSUE THREAD

**Issue by unseensnick** [gotson/komga#1025]
### Describe your suggested feature

Like the title says it would be nice to have the option to read manga directly from komga without having to download it first.

### Other details

Additionally this feature might (hopefully) also help with getting metadata to the manga series since the external sources from netsky atleast also shows metadata about the manga series, atleast how I have understood it from using paperback.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by darthmooguy** [comment]
If you are a Paperback user, why not just use netsky's sources directly? If it's because you want a similar experience on a PC, or you want a server like Komga so it works on multiple devices but has support for manga sources, it sounds like what you want is [Tachidesk](https://github.com/Suwayomi/Tachidesk-Server). Komga isn't a manga/comic/etc downloader, and probably never will be.

It's also worth noting that Paperback and Komga are two completely unrelated projects, with different teams working on them. The only link between them is that Komga is the only officially supported extension for Paperback, but it's maintained by the Paperback team, not gotson.

As far as metadata goes, Komga is currently bring your own metadata. This means you need external tools to fetch that metadata, for example [Manga-Tagger](https://github.com/Snd-R/komf) or [komf](https://github.com/Snd-R/komf).

**Comment by unseensnick** [comment]
> If you are a Paperback user, why not just use netsky's sources directly? If it's because you want a similar experience on a PC
> 
yes, it's because I want a similar experience on pc.
>
> Komga isn't a manga/comic/etc downloader, and probably never will be.
>
that part is clear from the start, this feature isn't about making it so you can download the manga directly from komga but more about getting the metadata and be able to read the newest chapter without having to find "drm free/legal" copy of it and downloading it.
>
> It's also worth noting that Paperback and Komga are two completely unrelated projects, with different teams working on them. The only link between them is that Komga is the only officially supported extension for Paperback, but it's maintained by the Paperback team, not gotson.
> 
yeah I know, It was just a suggestion.
>
> As far as metadata goes, Komga is currently bring your own metadata. This means you need external tools to fetch that metadata, for example [Manga-Tagger](https://github.com/Snd-R/komf) or [komf](https://github.com/Snd-R/komf).
>
yup, which is a little annoying at times but what can you do.

**Comment by darthmooguy** [comment]
> yes, it's because I want a similar experience on pc.

Then I'll point you again to Tachidesk or Mango, those already do what you want. (Tachidesk being a desktop reimplementation of Tachiyomi for desktop compatible with it's extensions, the Android equivalent of Paperback, and mango bring more similar to Komga in nature but also supporting external manga sources directly)

**Comment by gotson** [comment]
No plans to do that, Komga is a media server, you need your own files.
