### ISSUE TITLE
[Feature Request] Per User API Key

### ISSUE THREAD

**Issue by frameset** [gotson/komga#107]
### Is your feature request related to a problem? Please describe.
Having a way to send authorised requests to the API without having to log in first and get a cookie would greatly increase flexibility and interoperability. It would also allow you to revoke access to authorised apps by requesting a new API key, rather than having to change your password.

### Describe the solution you'd like
API key functionality would include extending the API spec so every command has an API key parameter that takes a user's API key to make sure the request is allowed.

You'd need some user interface additions to allow users to see their key in the web interface, and some way to revoke and generate a new API key in the web interface.

### Describe alternatives you've considered or other apps that can do what you want
Using a cookie is an alternative, but not as "clean".

### Additional context
The main reason I am requesting this is so I can have my comic post-processing shell script send an API request to scan the library again, so that new comics will immediately be available in Komga.

To extend the Plex paradigm Sonarr and Radarr support this functionality when a movie or TV programme is processed, they have Plex add the new item immediately.

It could also be used as an easy way to authenticate with potential native mobile apps.

**Comment by gotson** [comment]
Not saying api keys don't have their pros, but you don't need to use cookies to authenticate via api. The api is using http basic authentication, you can pass the login and password with every request, it will achieve the same result as API keys.

**Comment by frameset** [comment]
That's fair. It would require me to store the credentials in plaintext, but it does make it possible for me to do what I want. It's up to you if you think API keys are worth it I suppose.

**Comment by gotson** [comment]
Api keys are also credentials, they achieve the exact same purpose as basic Auth for the limited scenario. You will also need to store then in plain text. Actually they don't need to be stored in plain text, they just need to be decrypted before being sent, which I'd slightly different, but comes to almost the same thing because if you want to decrypt at runtime you need another key for that, which in turn will be in plain text..

Of course having api keys with limited scope and easy revocation can make them more powerful, but in the context of Komga that doesn't bring much value.

Ultimately the best solution to delegate access without providing secrets is to use Oauth2. This is something I would like to setup, but there are some caveats. First, OPDS doesn't support it. There's a draft for it, but even if it was accepted and released, none of the existing opds clients would implement it (they barely implement OPDS properly..). The same goes for Tachiyomi, which at the moment has limited options for authentication. If it was just opds we could limit the use of basic Auth to the /opds endpoints, but tachiyomi is using the rest api directly, and it would be a lot of work to segregate the api in 2, just so that Tachiyomi could use basic Auth, and the rest api use oauth2. 

I'm waiting to see what Tachiyomi 1.0 will bring, hopefully more flexibility for extensions in which case I would implement oauth2 and limit basic Auth to opds. 

I'll be closing this for now.

**Comment by frameset** [comment]
Good points, plenty to think about.
