### ISSUE TITLE
Fails to start/endless loop

### ISSUE THREAD

**Issue by X-Xadro** [gotson/komga#1109]
### Steps to reproduce

1. Execute docker-compose from portainer with latest version
2. container starts but log shows endless loop with jave sql errors
3. have to manually stop or else CPU stays high forever

### Expected behavior

Starting like before

### Actual behavior

Errors

### Logs

Log:

[komga-log.txt](https://github.com/gotson/komga/files/11239853/komga-log.txt)

### Komga version

0.165.0

### Operating system

Raspbery OS / Raspberry Pi 4B

### Other details

It's probably something on my end because Komga used to work until i ran some updates (2 months worth or so) and i also updated Portainer where i run the docker-compose from with stacks. It worked without a hitch before that.

I also tried the docker create command from the website and resulted in same errors.

I have tried looking up the errors but most went over my head honestly because i'm quite new at this.

In one issue that closely resembled my problem the docker version was requested so:

[docker-version.txt](https://github.com/gotson/komga/files/11239856/docker-version.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
You docker says it's Linux arm but within the container it's detected as Linux arn64.

You probably have a raspberry pi where the userland is not matching the system, one being 32 bits while the other is 64 bits.

**Comment by X-Xadro** [comment]
How would one go about fixing that? I mean it used to work before i performed updates after all

**Comment by X-Xadro** [comment]
`pi@Xadro-Pi4B-4GB:~ $ uname -m
aarch64
`

The OS seems to be running 64 bit it seems.

**Comment by briandking** [comment]
I am having the same issue on my RPi4 after installing the latest patches. It looks like it upgraded the kernel to 64 bit, but not many of the tools and libraries, As a consequence `uname -m` returns aarch64 now; but docker being 32 bit, still pulls down the 32 bit image.

When the 32 bit image runs, java 32 bit starts, but it detects the 64 bit architecture and tries to load the 64 bit sqlite library but the 32 bit java can't use it and complains about `wrong ELF class: ELFCLASS64`.

I tried forcing docker to grab the 64 bit image (`export DOCKER_DEFAULT_PLATFORM=linux/arm64`), and it will pull it down, but it fails to start or log anything at all. It just silently fails. Probably because docker is 32 bit.

**Is it possible to have the code that detects which sqlite library to load, to ignore the 64 bit options if the java itself is 32 bit?**

If not, as end users (for anyone else having this issue), I think the possible solutions are to either:

- Do as the person with [bug 354](https://github.com/gotson/komga/issues/354) did and re-install their Pi4 as 64 bit; OR

- Roll back the kernel patches. I haven't tested this yet, and using this option likely means you can't patch the kernel anymore or things will break again. I believe the patches that likely broke things for me are these (or a subset of them):
```
	2023-05-05 20:03:48 upgrade libraspberrypi-doc:armhf 1:1.20220308~buster-1 1:1.20230425~buster-1
	2023-05-05 20:04:00 upgrade libraspberrypi-dev:armhf 1:1.20220308~buster-1 1:1.20230425~buster-1
	2023-05-05 20:04:30 upgrade raspberrypi-kernel:armhf 1:1.20220308~buster-1 1:1.20230425~buster-1
	2023-05-05 20:10:45 upgrade libraspberrypi-bin:armhf 1:1.20220308~buster-1 1:1.20230425~buster-1
	2023-05-05 20:10:52 upgrade libraspberrypi0:armhf 1:1.20220308~buster-1 1:1.20230425~buster-1
	2023-05-05 20:11:02 upgrade raspberrypi-bootloader:armhf 1:1.20220308~buster-1 1:1.20230425~buster-1
	2023-05-05 20:11:36 upgrade linux-libc-dev:armhf 1:1.20220308~buster-1 1:1.20230425~buster-1
```

**Comment by briandking** [comment]
After looking at the documentation for xerial/sqlite-jdbc, I see it is possible to [override the architecture detection](https://github.com/xerial/sqlite-jdbc/blob/master/USAGE.md#override-detected-architecture).
Komga starts fine if I override the docker entrypoint and provide the architecture on the CLI. E.g.:

```
docker run --rm --entrypoint java gotson/komga -Dorg.sqlite.osinfo.architecture=armv7 org.springframework.boot.loader.JarLauncher --spring.config.additional-location=file:/config/
```

As a feature request, would it be possible to expose that override as an environment variable in the docker image? E.g.
```
-e SQLITE_ARCH=armv7
```

**Comment by gotson** [comment]
> As a feature request, would it be possible to expose that override as an environment variable in the docker image? E.g.

There's no need for that, you can use the `JAVA_TOOL_OPTIONS` environment variable for that purpose.

**Comment by briandking** [comment]
Thanks! Not sure how I missed that option. I just verified that it does work to fix this issue.
Adding the following to docker-compose.yml has Komga in docker on a Pi4 with a 64 bit kernel but 32 bit docker, in working order again:

```
    environment:
      - JAVA_TOOL_OPTIONS=-Dorg.sqlite.osinfo.architecture=armv7
```

**Comment by gotson** [comment]
@X-Xadro I am closing this as this is a user env problem, and workarounds have been mentioned.

**Comment by briandking** [comment]
One more update for future users stumbling on this. The workaround is no longer required after another set of raspberry pi patches were released. Installing these made the behaviour go back to normal
```
2023-05-15 22:39:57 upgrade libraspberrypi-doc:armhf 1:1.20230425~buster-1 1:1.20230509~buster-1
2023-05-15 22:40:18 upgrade libraspberrypi-dev:armhf 1:1.20230425~buster-1 1:1.20230509~buster-1
2023-05-15 22:40:20 upgrade raspberrypi-kernel:armhf 1:1.20230425~buster-1 1:1.20230509~buster-1
2023-05-15 22:45:51 upgrade libraspberrypi-bin:armhf 1:1.20230425~buster-1 1:1.20230509~buster-1
2023-05-15 22:45:52 upgrade libraspberrypi0:armhf 1:1.20230425~buster-1 1:1.20230509~buster-1
2023-05-15 22:45:56 upgrade raspberrypi-bootloader:armhf 1:1.20230425~buster-1 1:1.20230509~buster-1
2023-05-15 22:46:46 upgrade linux-libc-dev:armhf 1:1.20230425~buster-1 1:1.20230509~buster-1
```
