### ISSUE TITLE
Edit all books metadata from Series edition dialog

### ISSUE THREAD

**Issue by gotson** [gotson/komga#114]
Allow edition of book metadata from the Series edition dialog:
- those changes will apply to all books of the series
- fields:
  - authors
  - reading direction
  - publisher
  - age rating

**Comment by GlassedSilver** [comment]
Can we have this work in such a way that it also will update future additions to that series?

Ongoing manga released chapter-per-chapter I don't wanna keep updating. If a given book were to have metadata deviating from the series level it should just be an override/manual replacement.

**Comment by GlassedSilver** [comment]
Maybe even smarter would be to be able to convert a series (and its folder) to a book.

So chapter-level separated manga that form "one book". Preferably we could set this style of management "chapter-based files" per library and per book. (because even in a manga library you may have a few oddballs that you add as [tankobons](https://en.wikipedia.org/wiki/Tank%C5%8Dbon)).

**Comment by gotson** [comment]
> Maybe even smarter would be to be able to convert a series (and its folder) to a book.
> 
> So chapter-level separated manga that form "one book". Preferably we could set this style of management "chapter-based files" per library and per book. (because even in a manga library you may have a few oddballs that you add as [tankobons](https://en.wikipedia.org/wiki/Tank%C5%8Dbon)).

That would be more complex and would need to be another issue entirely.

**Comment by GlassedSilver** [comment]
> 
> 
> > Maybe even smarter would be to be able to convert a series (and its folder) to a book.
> > So chapter-level separated manga that form "one book". Preferably we could set this style of management "chapter-based files" per library and per book. (because even in a manga library you may have a few oddballs that you add as [tankobons](https://en.wikipedia.org/wiki/Tank%C5%8Dbon)).
> 
> That would be more complex and would need to be another issue entirely.

I'll merrily create the issue for trackability, I wanted to think aloud first in here though because I saw some relevance and didn't want to create an issue for something that may get rejected at the thought process stage already. :P 

Guess I'll create it then? :)

**Comment by gotson** [comment]
Go ahead.

Having different kind of scanners per library type is something Plex does already (movies are not scanned the same way tv shows are).

This is also something that floated around when some people complained about the scanning for their library which was in the Humble Bundle format (with multiple sub-directories per file format). Having a scanner per library type, when the library type is meaningful, is not something i'm against, to the contrary!

**Comment by GlassedSilver** [comment]
Cool, will go ahead with creating it then!

I wasn't so sure on how supportive you are of this, given that this issue where I mentioned chapter-based manga storage was cut off from public discussion after a certain someone left a very rushed remark, going as far as implying I'm a pirate with no way to comment on that. (link to comment in question: https://github.com/gotson/komga/issues/116#issuecomment-614611403)

I was confused that their comment remained up whilst I didn't get to defend myself.

By now I'm not even interested anymore in arguing with them, I think manga aficionados know why and it's not just piracy that would cause this to be a relevant use case.

Either way, I'm going off-topic. I guess I wanted to say something about their rudeness after all. Since this is off-topic, feel free, if you want to, to delete this very comment right here. No hard feeling at all. I guess I just mostly wanted to relay this information to you specifically. Since I don't see your email or Twitter listed on your profile I guess a comment like this may fit as well.

**Comment by gotson** [comment]
Thanks for opening up, i have just deleted that particular comment which had no place here. I close some discussions when it's getting off-topic as you noticed. This is no place for those kind of debate, and i would add that arguing in those situations is pointless, but that's my opinion.

I am supportive of everything that is bringing value to Komga in a way that is relevant, well designed, and supporting the long term vision i have for it (which is not always very clear to people requesting features, and me denying those requests). I am also a supporter of fansubbing and scanlations for content that is not available officially, and this particular case would perfectly fit here for chapters library.

**Comment by GlassedSilver** [comment]
Love your stance and glad we see eye to eye. Just created the issue by the way. Hope I made my ideas about that feature clear enough, if not, I'll be happy to clarify and of course also am curious as to what you have to say about those ideas. I'm sure the concept may have rough edges and can be rounded off a bit. Hope it's a good starting point. :)

**Comment by gotson** [comment]
Given _reading direction_, _publiser_ and _age rating_ have been moved to _Series_ level, and given _Series_ now aggregates metadata from its _Books_, I don't think this is necessary anymore.

Adding authors on the first book should be enough to have aggregated authors at series level.
