### ISSUE TITLE
Reading direction by Series

### ISSUE THREAD

**Issue by gotson** [gotson/komga#116]
A reading direction at Series level that would apply to all books in this Series that do not have a reading direction set.

This would remove the need to set reading direction for each book, especially when new books are added to an existing series.

**Comment by GlassedSilver** [comment]
This would come in handy for those of us who read manga as well as Western comics.

Manga are typically added as chapters to a series, not as volumes. (at least I don't know anyone personally who stores their manga by volumes)

That also means that series should have all of the metadata that you can set on a per-book level per series, because depending on what you read, that's where the action is, the series-level. In general.

**Comment by Gin-no-kami** [comment]
@GlassedSilver People who actually purchase their manga have them as volumes, as thats how they are sold on places like bookwalker and amazon.

**Comment by gotson** [comment]
Closed in favor of #276
