### ISSUE TITLE
[Feature Request] Add detection for double page spreads during media analysis

### ISSUE THREAD

**Issue by whalehub** [gotson/komga#123]
### Is your feature request related to a problem? Please describe.
The official digital release of most, if not all manga has double page spreads stitched together into one image. The problem in Komga's web reader right now is that if you open a manga like that with Double Page mode turned on, both the double page spread and the next single page are displayed simultaneously which messes up the white space that is normally between single pages from that page forward.

Example: https://i.imgur.com/A7e2kMW.jpg

### Describe the solution you'd like
Since Komga already analyses all media files, it should be relatively simple to add a check for whether a page's width is greater than its height and marking such pages as a double page spread. The web reader would then have to display pages which have been marked as a double page spread by themselves in Double Page mode.

### Describe alternatives you've considered or other apps that can do what you want
I could split all double page spreads into two pages to fix this issue but that would be a massive waste of time since the problem lies with the client app. The image viewer Honeyview, for example, correctly recognizes double page spreads in Double Page mode and displays them by themselves.

### Additional context
N/A

**Comment by gotson** [comment]
Kind of linked to #40

**Comment by whalehub** [comment]
@gotson Any news on this?

**Comment by gotson** [comment]
I can to give ETAs as a general rule, but this one is clearly not at the top of the priority list.

**Comment by whalehub** [comment]
@gotson Just wanted to ask, would you be open to someone sponsoring this feature?

**Comment by gotson** [comment]
I cannot do sponsorship, as I have a full time work and don't need the money for myself.

All donations are still greatly appreciated and will be used to fund other open source projects that Komga relies on.

You can check the open collective page (link on top in the sponsors button) for more details on my current plans on that front.

**Comment by gotson** [comment]
Thinking about this enhancement, the detection during media analysis is the easy part. Handling how to order the pages in the webreader is a bit harder.

At the moment, the webreader retrieves the list of all pages first. Then if it is configured in double page mode, it will display like this:
- page 1 alone
- 2 pages on the same page
- if the page count is odd, last 2 pages
- if the page count is even, last page

It does that by simple computations, but to handle wide pages that could happen anywhere, we need a deterministic method to map a list of pages to a list of displayed pages. The list of displayed pages would contain arrays of 1 or 2 pages to display.

We also need to be able to convert an absolute page number to a displayed page number, so that we can jump to a page, or resume progress.

--- 

For example if we have 11 pages, and 2 and 4 are wide, we would get: 

```
[[1],
[2],
[3],
[4],
[5,6],
[7,8],
[9,10],
[11]]
```

In order to convert an absolute page number to a displayed page (here 5 => 5, 8 => 6), we can keep the page object containing its absolute number in the target structure, perform a find, and get the index. Or maybe just build a map at the same time we build the structure.
