### ISSUE TITLE
Add "order by filename" to the series page (StoryArc related)

### ISSUE THREAD

**Issue by cesalo** [gotson/komga#134]
### Is your feature request related to a problem? Please describe.

This is related with the Story Arc functionality. I've seen this mentioned in this feature #106 and also in this ticket: https://github.com/gotson/komga/issues/30#issuecomment-578343923
Regardless of this: Mylar has its own version of this and it creates a new folder with symbolic or hard links base on the series that belong to a StoryArc. It has also an option to pre-append the # in the StoryArc to the original filename, for example for the StoryArc Civil War would be:

- 001-Free Comic Book Day 2016 (Civil War II) 001 (2016)
- 002-Civil War II Ulysses Infinite Comic 001 (2016)
- 003-Civil War II Ulysses Infinite Comic 002 (2016)
- 004-Civil War II Ulysses Infinite Comic 003 (2016)
- etc.

At the moment Komga finds the StoryArc folder but its ordering options are: Number, data added or filesize so the reading order is not correct:
![Screenshot from 2020-04-06 12-38-40](https://user-images.githubusercontent.com/16859916/78582647-9ea3ee80-7803-11ea-8873-ee738a9b94d5.png)
The problem would be solved if filename was included in the "order by" options.
### Describe the solution you'd like
Order a series by filename.

**Comment by gotson** [comment]
Hi, before jumping to the solution, can you explain a bit more the actual problem?

In the explanation you wrote you give an example with 4 files, then in the image you show many more files that are coming from apparently different series. I also see those files have the same issue number 1, which i suppose is coming from `ComicInfo.xml` ?

I am not very familiar with the Story Arc concepts of those big Marvel/DC series, could you walk me through this particular example, explaining where the different issues are coming from exactly, like other series?

Can you also explain what happens when Mylar creates new folders with links? Does that mean you have the same file in 2 folders on your disk?

**Comment by cesalo** [comment]
In the explanation you wrote you give an example with 4 files, then in the image you show many more files that are coming from apparently different series. I also see those files have the same issue number 1, which i suppose is coming from ComicInfo.xml ?

> Mylar takes the information of the Story Arc from Comicvine: https://comicvine.gamespot.com/civil-war-ii/4045-58879/issues/
> The Story Arc is spread in different series jumping between them as the story develops. There is a issue number within the Story Arc and then the issue number within the series. Yes the issue number is coming from the Comicinfo.xml for the series and Comicvine for the Story Arc.

I am not very familiar with the Story Arc concepts of those big Marvel/DC series, could you walk me through this particular example, explaining where the different issues are coming from exactly, like other series?

> That's correct. Check the link I provided in my previous answer. For example Civil War II is spread in several Series like:
> - Civil War II: Ulysses Infinite Comic
> - International Iron Man
> - Captain America: Sam Wilson
> and many more.
> 

Can you also explain what happens when Mylar creates new folders with links? Does that mean you have the same file in 2 folders on your disk?

> Mylar has 2 options symbolink links or hardlinks. I personally use hardlinks but either way Komga should be able to see both files as different files in different folders (Mylar creates a folder for each Story Arc).

Also, where does Mylar gets the data about those Story Arcs ?
> Comicvine: https://comicvine.gamespot.com/civil-war-ii/4045-58879/issues/
> There is a StoryArc tab in Mylar where you can search Story Arcs and then validates what series you have already in your library and the generate the links in a different folder using the order of the Story Arc.

Adding a screenshot from Mylar with the first page of this Story Arc just to give you an idea:
![image](https://user-images.githubusercontent.com/16859916/78624208-16e7cf80-7857-11ea-903e-6622612b1ab8.png)

**Comment by gotson** [comment]
Thanks for the detailed explanation!

There is one issue with the use of links in Komga: books will be duplicated, in 2 different series. Those books will live their own lives as separate entities, with different metadata etc.

Ideally books should not be duplicated, and instead as you mention there should be a feature to handle Story Arcs within Komga, grouping books into a Story Arc, along with a number for the position.

It is not clear however how this could be automated, apart from having a ComicVine scrapper (which is planned but will take time).

In the `ComicInfo.xml` [schema](https://github.com/gotson/komga/blob/27239c3846dc56355f6e3b69b3b634305536a036/komga/schema/ComicInfo_v2.xsd#L38) there is a field for the StoryArc, but nothing about the order, which rules out this source of metadata as a source of truth to rebuild the StoryArc within Komga altogether.

---

In the meantime, books are duplicated, and if you are fine with that, and since they are their own entities, you could use the book number to reorder them within the Story Arc. Actually this would have worked nicely before `0.25.0` since the number would have been deduced from the filename, but with the import of metadata from `ComicInfo.xml` it uses the original issue number instead.

I see a few options here:
1. as you mentioned, be able to use `book.number` (this is the integer representation of the index of files in the folder)
  - Pros:
    - it solves the UI problem
  - Cons:
    - it doesn't solve sorting in all the other medium: OPDS feed, API via Tachiyomi
    - it introduces a UI element that is very specific to this particular use case, and could confuse users
2. update the metadata for books in the Story Arc folder, and use it to re-order according to filenames
  - Pros:
    - it solves sorting everywhere
  - Cons:
    - it's not automatic, you have to write a script that does that for you. Every new addition of books in the folder will need to be post-processed in this way.
3. prevent the books in a Story Arc series to retrieve metadata from `ComicInfo.xml`
  - Pros:
    - the numbering would default to the one from the filenames
  - Cons:
    - you will not have any metadata on those books
    - it would require to add some kind of optional behaviour per series for the metadata sources, which is not something I planned for, and don't really want to implement it at the series level (a library level maybe).

2 seems the easiest in terms of code (no change), it also solves the problem in a nicer way (everywhere), but requires some work on your end (scripting), and also need to be triggered every time a book is added, however this can be automated.

Please let me know what you think about all this.

By the way, does Mylar offer hooks or scripting that could be used to enrich tis workflow?

**Comment by cesalo** [comment]
I agree that having this handled by the Comic server is the best option but is the hardest to implement as you said. This is one of the downsides of using Mylar for this since is not used to actually read the comic but for the same reason I don't think number 2 is a good idea as Mylar is in charge of that part. If I change that manually it will affect the Mylar section for the Story Arc that shows both values: series issue number and Story Arc issue number. I just checked and Ubooquity has order by path which is why is showing the Story Arc in order.
I don't agree that adding an order by path or filename will confuse users also don't think this is the only case for this feature. I honestly don't read Mangas, that seems to be the main focus of Komga, but I do see a lot of future for comics users transitioning from Ubooquity to Komga which may find this option very useful.
Anyway I just thought it was something that needed to be brought up to your attention. Thanks for the feedback and I'll be very pending of the next features of Komga.

**Comment by gotson** [comment]
> If I change that manually it will affect the Mylar section for the Story Arc that shows both values: series issue number and Story Arc issue number

I think there is a misunderstanding, what i am proposing is to update the metadata inside Komga only. That wouldn't affect the files, nor Mylar.

What i am proposing is the following:
- prerequisite: be able to distinguish folders containing normal series from Story Arc folders. I think in Mylar you can choose where to put those, so you could choose a single parent folder to group all the Story Arc folders.
- write a script that would:
  - retrieve all the Series from Komga, via the API
  - filter to keep only the Series for which the directory is a subdirectory of the Story Arc parent folder. This would be a simple comparison to check that a path is contained into another.
  - then for each Series that is a Story Arc series:
    - retrieve the list of all books in that series
    - sort the list by filename
    - for each book, update the metadata `numberSort` field with the computed index

This script could run automatically, either on a periodic schedule, or triggered when changes are detected in the Story Arc folder. That's why i was asking about Mylar offering any hooks, for example if Mylar could trigger a script after it changes something on disk, you could use it to trigger the script.

> I don't agree that adding an order by path or filename will confuse users

You may not agree, still since the path/filename is not a primary concept in Komga, it would bring confusion.

> also don't think this is the only case for this feature

What other case is there for that?

> Mangas, that seems to be the main focus of Komga

It is not. Komga is not focusing on any particular genre of graphic novels.

**Comment by cesalo** [comment]
> I think there is a misunderstanding, what i am proposing is to update the metadata inside Komga only. That wouldn't affect the files, nor Mylar.

Got it. Thanks for the clarification. This is a great idea and I'll look into it.

> What other case is there for that?

Old comics that don't have metadata and rely on file-name for ordering.
Magazines as well. I know is not the primary concept but eventually everybody tends to use the best tool for similar tasks. Currently I have Ubooquity to handle comics, books and magazines.
Now Magazines can relay on creation date for ordering purposes but in my case I need to compress them or switch the first 2 pages (cover is in 2nd page) or fix a wrong issue. For these reasons relying on file-name for ordering is more resilient.

> It is not. Komga is not focusing on any particular genre of graphic novels.

Even more reason to have an extra way of ordering as it will handle a broader type of file types.

Also would like to highlight that just realized that Ubooquity only orders by file-name (path) or creation date. The fact that Komga is using issue number as default makes it a more solid/robust alternative (IMO) but that doesn't mean that there is no room for other order options that may have a smaller case. Anyway I'll look into the script you proposed.

**Comment by gotson** [comment]
> * Old/not-common comics that don't have metadata and rely on file-name for ordering maybe even personal scans of old stuff
> * Comics from other countries specially Latin-America that are not in Comicvine ( and won't be :( ).
> * Magazines as well. I know is not the primary concept but eventually everybody tends to use the best tool for similar tasks. Currently I have Ubooquity to handle comics, books and magazines. Now Magazines can relay on creation date for ordering purposes but in my case I need to compress them or switch the first 2 pages (cover is in 2nd page) or fix a wrong issue. For these reasons relying on file-name for ordering is more resilient.

If there is no metadata, then the default sort _is_ the filename sort. When Komga scans series and books, it will order the books by filename, using natural sort, and set the metadata number with that information. You are free to change it afterwards, but if you don't touch anything, books without metadata will be ordered by filename.

---

If you need help with the script or API, please reach out on Discord, i would be happy to help!

**Comment by cesalo** [comment]
Thanks for all the help. I have created the scripts and at least they are doing what I need - Nothing fancy just pure functionality. I put the scripts here in case somebody else needs something similar:
https://github.com/cesalo/komga_storyarc_sort

**Comment by gotson** [comment]
Glad you got it working ! I'll close the issue for now.
