### ISSUE TITLE
The reading progress of the epub file cannot be synchronized

### ISSUE THREAD

**Issue by Benjamin-Watson0** [gotson/komga#1377]
### Steps to reproduce

1. Download the Windows client and deploy it locally
2. Add the epub file and start reading
3. The Android phone accesses the epub file through the LAN and finds that the reading progress is not synchronized
PS: I've tested the pdf file and the reading progress sync is good

### Expected behavior

Android phones access epub files through LAN and find that reading progress can be synchronized

### Actual behavior

The Android phone accesses the epub file through the LAN and finds that the reading progress is not synchronized

### Logs

[komga.log](https://github.com/gotson/komga/files/13817829/komga.log)

### Komga version

v1.9.2-master

### Operating system

Windows 11

### Installation method

from download.komga.org

### Acknowledgements

- [X] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/docs/faq).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
can you provide that particular book file that has issues ?

**Comment by gotson** [comment]
works well for me. in order to troubleshoot further we would need some more details on which API calls the client is making.

can you try with a desktop browser and see if you have the same issue ? Are you using a reverse proxy or hitting directly the Komga server ?

**Comment by gotson** [comment]
could be fixed with ec97da651df3f587b4943311db73b570eef70e66

**Comment by gotson** [comment]
without logs or api call details or something there's not much i can do unfortunately

**Comment by gotson** [comment]
you can try to get traces of the HTTP exchanges from `/actuator/httpexchanges` and look for PUT calls to `/api/v1/books/{bookId}/progression`

**Comment by ressiv** [comment]
I've found a similar situation sync'ing epub reading progress between two Apple-based devices and can replicate this consistently.  (1.10.4-master on MacMini M1)
1. Advance book progress on device1.
2. Tap screen and use arrows to exit reader.  Return to Komga home screen.
3. Return to book page on device1 and verify reading progress is consistent with expectation.
4. On device2, access the same book page.
5. Reading indicator  will indicate consistency with device1's reading progress.
6. Open book on device2 to read and it opens to the cover page rather than the expected page from device1.

Replicating these steps between Safari and Firefox on the same device doesn't seem to trigger the loss of read progress sync.  
This occurs when using any permutation of Safari and Firefox on either device.
Only occurs between devices for some reason? 
Occurs with every epub I've tried this with - doesn't seem to be specific to the epub.

I tried tracing this but have never used a debugger in Firefox before and got pretty lost.... hopefully these clues help?
