### ISSUE TITLE
Option to hide password login if SSO login option(s) implemented

### ISSUE THREAD

**Issue by gnouts** [gotson/komga#1395]
### Describe your suggested feature

I have SSO with Authelia setup, I'd like to hide the email/password prompt on the web interface since it just confuses my users. They try to login as normal user (which doesn't exist) instead of clicking through the "Signin with Authelia".
Having a config that can hide the normal login prompt would be nice.

Mostly the same as https://github.com/gotson/komga/issues/1197 which targeted another use case.
So I don't really care about third party apps login or actually disabling the api login. It's just a userfriendly feature request.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
> They try to login as normal user (which doesn't exist)

that's wrong. There is always a Komga user, even though the user may not know the password.

**Comment by gnouts** [comment]
I think I explained it wrong and this is a valid request. Or maybe the feature already exists but I missed it.
Either way, what I was saying : Once OAuth is enable, I'd like to hide the password prompt on the login page. That was the relevant part of my request (and not the fact a user existed or not, or knew their password or not).

And I double-checked in case I missed it, but even if the user exists, if it was created by OAuth integration, the password login doesn't work for them. They have to use the "Sign in with Authelia" button.
What I meant by "normal user" was to login through the email/password prompt. If they try that, I can see a failed login attempt from the `source` "password".

Please reconsider opening this issue

**Comment by gotson** [comment]
Even if the user is created by OAuth2, it does have a random generated password. Which can be changed when logged in (from OAuth2 for example). I will not implement this feature, that's all.

**Comment by gnouts** [comment]
Ho I just understood what you were saying earlier !
I don't know the OAuth2 spec so I might be wrong but from a pure sysadmin view, it feels so odd to be able to login both with OAuth and without it (once logged at least once with OAuth). To summarize : the user actually exists on Komga and on my LDAP server, resetting the password on Komga doesn't change the one on LDAP (happily!). So user can have a completely different password, where both are working in Komga.
That's a bit hard to understand, I'm not sure I've seen that pattern elsewhere. But anyway that was still not my point :sweat_smile: 

> I will not implement this feature, that's all.

That's fair, I can understand that. I mean, I won't either :smile:

**Comment by gotson** [comment]
It seems you don't understand exactly how delegated auth works.

The Komga user exists, whether you use OAuth2 or not. This is needed because Komga stores a lot of things in regards to a user, like the read progress, the permissions etc.

When you trigger OAuth2 login, you delegate the authentication to another system, here Authelia. What OAuth2 does is verify that the user is who he says he is (email address here) and is correctly authenticated. Then returns a OAuth2 token back to the app.

When Komga receives the OAuth2 response, it checks that a user exists with this email, and if there is one, it generates a login session, exactly as if you logged in with the password. It's just a different way to authenticate.

And you can still authenticate with the password, or with any other OAuth2 provider configured (for instance you could have Google + Github + Facebook + Authelia).

**Comment by gnouts** [comment]
Thanks for taking the time to explain that ! This means, if a user uses the same email on Google, Facebook and Authelia, they can authenticate by any of those three providers, and still end up on their (unique) profile inside Komga ?
That makes sense. And it's actually very understandable when you know Komga uses email as a unique ID.

Though, from a user perspective (at least my users, who aren't very tech-literate), it might be confusing. Most of them just try to login at least twice with the password (which was set randomly on Komga internally, I understand that now) before trying to login through the OAuth provider.
(I mean the other way around would be just as confusing, if Google/Facebook/etc login buttons were always shown but none would work because not configured by the admin)
I think we can agree on that, even if that's a `wontfix`.

**Comment by gotson** [comment]
> This means, if a user uses the same email on Google, Facebook and Authelia, they can authenticate by any of those three providers, and still end up on their (unique) profile inside Komga ?

yes, exactly.

This is a common behaviour on many apps, where you can login with your social media account, that's what actually happens.

> Though, from a user perspective (at least my users, who aren't very tech-literate), it might be confusing. Most of them just try to login at least twice with the password (which was set randomly on Komga internally, I understand that now) before trying to login through the OAuth provider.
> (I mean the other way around would be just as confusing, if Google/Facebook/etc login buttons were always shown but none would work because not configured by the admin)

That kind of confusion would happen on any other site that does social media login.

For instance this is the sign-in dialog of Kayak.com:
<img width="480" alt="image" src="https://github.com/gotson/komga/assets/2139133/d10f86c8-e3d6-44f1-9a0b-86434838a0e9">

You can argue that because you control the Komga instance, you may want to hide the password field, but as mentioned i don't believe that's a feature worth developing.

`wontfix` doesn't mean it's not valid, it's just that i will not take the time to do it.
