### ISSUE TITLE
Documentation on how to run as a Windows Service

### ISSUE THREAD

**Issue by gotson** [gotson/komga#142]
It would be great to have some documentation explaining how to install Komga as a Windows Service, which would start when the Windows machine starts.

**Comment by ArathoN** [comment]
Hi, this is how i'm running komga as a windows service using nssm.
First I installed NSSM through chocolatey `choco install nssm` 
Then take note of java and komga directory and run these commands in powershell or command prompt AS ADMINISTRATOR:
`nssm install Komga "**C:\Program Files\OpenJDK\openjdk-11.0.5_10\bin\java.exe**" "-jar **C:\PortableApps\komga\komga.jar**"`
`nssm set Komga AppDirectory "**C:\PortableApps\komga**"`
`nssm set Komga Start SERVICE_AUTO_START`

I had some issues with the password generation and I had to force it manually with this command:
` java -jar komga.jar --spring.profiles.active=claim`

For now is working wonderfully and whenever i need to update i stop the service with 
`nssm stop komga`
replace the jar file and start the service
`nssm start komga`

I would love a system to update automatically
I hope this is helpful.

**Comment by gotson** [comment]
That's a good start, thanks for your input.

How did you install Java OpenJDK11 ? Via Chocolatey also?

**Comment by ArathoN** [comment]
Yes. I use chocolatey to manage almost all my apps. The java installation should be the same as installing the file from java or openjdk. 
NSSM needs an additional step because the developer provides only the exe file which path needs to be added as an environment variable. This step is automated in chocolatey so you can check their [code](https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/nssm)

**Comment by andrelopesmrx** [comment]
I am not familiar with NSSM, but I use docker in a similar way.
