### ISSUE TITLE
[Bug] Thumbnail bug

### ISSUE THREAD

**Issue by yreb** [gotson/komga#150]
### Komga environment
- **OS**: 
- **Komga version**: 0.28.1

- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 

### Describe the bug
Some Thumbnails (Cover) are not displayed in komga, we have a woderful gray square to replace them. The problems appears sometimes (rescan the library is ineffective)

I tried to repack cbz with differents software / change compression settings => same problems each time

I tried to make a test cbz with only the cover image => nothing happens

I tried to convert my  webp cover in jpeg and compress it, then komga works

The cbz covers are perfectly displayed on windows but not in Komga

There seams to be à bug during the scan which is triggered sometimes when you cover is in a webP format

Besides this problem the webp cbz comic is perfectly readable

**Comment by gotson** [comment]
The library used in Komga to handle `webp` is quite limited, particularly it doesn't handle webp with transparency channels (alpha) or lossless (see this comments for more details https://github.com/gotson/komga/issues/68#issuecomment-572350213).

When you stream the pages, the images are not converted if your browser can handle webp, that's why they are showing fine. If your browser cannot handle webp, then Komga will convert it on the fly, and you would have the same issue.

The thumbnail is converted to `png`, and if the webp image cannot be read, the image will either not render, render an artefact, or render with improper colors.
