### ISSUE TITLE
[Bug] Specific pages not loading through OPDS API

### ISSUE THREAD

**Issue by Daedren** [gotson/komga#153]
### Komga environment
- **OS**: Debian Stretch
- **Komga version**: 0.28.4
- [x] **I am running Komga with Docker**
  - Docker image tag [e.g. latest, beta]: 0.28.4
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [ ] **I have a problem in the web interface**
  - Browser (with version): 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version):
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
Some specific .cbz books in my library don't load through the OPDS API.
Accessing the image through the API directly gives me a 200 OK, but with an invalid JPEG for a response.
Ex. /opds/v1.2/books/7904/pages/1?convert=jpeg&zero_based=true

**But removing the convert=jpeg querystring yields a valid image.**

komga.log doesn't provide any errors, just mentions it's converting the PNG page to JPEG.

### Steps to reproduce
1. Access the offending book through the OPDS API directly or a client that reads it (I also tested with Chunky on iPad)
2. Try to read a page.

### Expected behavior
The page should be returned by the API correctly

### Actual behavior
The API gives a 200 OK and returns just a few bytes that don't amount to a valid JPEG

### Log file
```
2020-05-07 18:46:10.948  INFO 1 --- [http-nio-8080-exec-6] o.g.komga.domain.service.BookAnalyzer    : Get page #1 for book: /books/xxx/23.cbz
2020-05-07 18:46:10.977  INFO 1 --- [http-nio-8080-exec-6] o.g.k.application.service.BookLifecycle  : Convert page #1 of book /books/xxx/23.cbz from image/png to image/jpeg
```
I'll send you the offending .cbz privately.

**Comment by gotson** [comment]
The problem is coming from the PNG images which have transparency (which is uncommon and useless for comics/mangas). As `JPEG` does not have transparency, the conversion fails.

When using the REST API, either via the webreader or via Tachiyomi, it's easier to detect the client capabilities regarding the different image types (for instance if it can read `webp`), and to convert only the images that are not supported. For example with a book that contains mostly `jpeg` and one `webp` file, when using the webreader on an older browser that doesn't support `webp`, only the `webp` image will be converted to `jpeg` on the fly.

For OPDS it is a bit more tricky, because the [OPDS Page Streaming Extension ](https://vaemendis.net/opds-pse/)specifies a single template to get all of the pages, and requires to indicate the **mediaType**:

> « type » MUST indicate the type of image returned by the server (value MUST be one of the following : "image/jpeg", "image/gif" or "image/png")

Given this limitation i made the choice to force conversion to `jpeg` for all images, that way the mediaType is the same for all the images.

---

An obvious fix would be to fix the books, but it seems more and more mangas sites use alpha channel in their images for some reason, and it's complicated to convert images without losing quality and keeping the filesize reasonable.

I could try to implement something for OPDS, which is:
1. check if all the images of the book are of the same type (we have the information already)
2. if `1.` is `true`, check that the image type is one of `gif`, `jpeg` or `png` (the formats supported by the OPDS PSE specification)
  - if `2.` is `true`, serve the images as-is, and mention this media type.
  - if `2.` is `false`, then we need to normalize images for the book, as it is done today.

Historically i was using `png` as the default conversion method, but the PNG encoders have some issues in some versions of Java, resulting in bigger filesize, that's why i switched to `jpeg`.

Another solution could be to use `png` as the default conversion for OPDS.

**Comment by gotson** [comment]
I have checked what can be done regarding images with alpha channel.

The interesting bit is that even though some formats can have alpha channel, it may not be used. For example on your image the alpha channel is present, but all pixels are opaque (transparency = 1). If it's the case then it's safe to convert to RGB Jpeg for example.

If images do have transparent pixels, then I could still convert and choose a background color, white for example.

I think i'll go down that route, it's better to get an image with small visual artifacts than a fat error :)
