### ISSUE TITLE
[Feature Request] Settings page

### ISSUE THREAD

**Issue by yreb** [gotson/komga#158]
Nas owner may have some problems when they want to change their settings, and may cause some issues

=> An advanced settings page (locked by the admin password) would be great. 

Other issue, on first install , searching in your nas root a random password is clearly not the easiest thing to do , you should create an alternative for that.

**Comment by gotson** [comment]
For the password you can use the [claim server mode](https://komga.org/installation/user-accounts.html#claim-server-mode).

Regarding the settings, can you clarify why it impacts NAS users specifically? What are those problems you refer to, and what are the issues they may cause?

**Comment by yreb** [comment]
You have to go on your root directory and edit files manually with nano or other text editors..... doing that may needs to bypass some security (There is a reason to hide that part of your NAS)

Advanced settings : port / proxy etc....., that could be a way to limits errors , Doing it in the user interface may inform you of the utiulity of each function, when a settings is wrong....

**Comment by gotson** [comment]
Most if not all the settings are a one-time configuration, not something you change everyday. 

Also, what you mention may be true for other systems too, and users should have access to their file system in order to perform such changes.

A process like Komga should not run as root, as such it should not require to bypass any security (I suppose you refer to sudo).

The documentation is there to inform about the utility of each function and the format to use.
