### ISSUE TITLE
[Feature Request] Summary field for a Series

### ISSUE THREAD

**Issue by bestrandomnameever** [gotson/komga#170]
Would it be possible to add a summary field for a Series. If this is a deliberate decision to not have it, what would be the reasoning behind it? While using Tachiyomi would be quite handy while perusing a collection.

**Comment by gotson** [comment]
Thanks for creating the issue, I planned to add it.

**Comment by cesalo** [comment]
This seems similar to #181 .. great idea.

**Comment by gotson** [comment]
Closed in favor of #276

**Comment by notSeaSmoke** [comment]
I see that this was closed in favor #276, however, while the current implementation displays the summary for the first title on the series page, the Summary field for the series itself is still blank. Therefore, Tachiyomi doesn't show the summary since it needs the Summary field for the series to be filled.

**Comment by gotson** [comment]
> I see that this was closed in favor #276, however, while the current implementation displays the summary for the first title on the series page, the Summary field for the series itself is still blank. Therefore, Tachiyomi doesn't show the summary since it needs the Summary field for the series to be filled.

Good call. Can you create a new issue for that?

**Comment by notSeaSmoke** [comment]
made one #391
