### ISSUE TITLE
[Bug] changing extension of a book issue

### ISSUE THREAD

**Issue by prysme01** [gotson/komga#182]
### Komga environment
- **OS**: windows
- **Komga version**:  0.35.1
- [ ] **I am running Komga from the `jar`**
  - Java version: 1.8
- [ ] **I have a problem in the web interface**
  - Browser (with version): firefox

### Describe the bug
If you change the extension of a book after the scan, you get an inconsistent grey book referenced in the UI, no way to get remove the book, you have to delete the folder and add it again

### Steps to reproduce
1. add a new book
2. scan the library
3. convert the book from cbr to cbz (or simply change the extension from cbr to cbz)
4. scan the library

### Expected behavior
komga should act exactly like it does when you rename the filename without changing the extension.
ui update and consistent behavior.

### Actual behavior
you get a stacktrace filenotfound and a grey book on the ui with no way to recover the situation without having to delete the folder

### Additional context
It happen when I convert cbr book to cbz by using comicrack on my existing library.

### Log file
https://gist.github.com/prysme01/88117d15a81bf7f663e5919fe3e7d387

**Comment by gotson** [comment]
The logs are from an analysis, not from a scan. Those are [separate processes,](https://komga.org/features/concepts.html#scanning) ran in sequence.

Analysis expects the path of the file to be accurate, else the exception you have in your logs will happen.

Scan is responsible to update file path.

I tested the steps you mention above and it works as expected, i suppose you used Analyze instead of Scan, which would indeed raised a FileNotFoundException.

I will close this for now, if you still have an issue you can reopen, but please attach a full log file, not just an excerpt.
