### ISSUE TITLE
[Feature Request] Store cover creators in book metadata

### ISSUE THREAD

**Issue by cesalo** [gotson/komga#184]
This is the way the metadata of the comic is shown in Komga:

![Screenshot from 2020-06-05 14-03-25](https://user-images.githubusercontent.com/16859916/83908743-9ac61700-a735-11ea-9370-160438d27396.png)

Everything is good up to the part that shows the covers and creators where the "table" is desaligned.
It would be great if we can choose a different font with uni-space like Courier or show that part with a different format.
I don't ready Mangas too much but almost all my comics have minimum a couple of rows on that section.

**Comment by gotson** [comment]
The information shown in the table is actually metadata, not descriptive text. I suppose it's stored in the description inside `ComicInfo.xml` because of the lack of a proper metadata structure to store this information properly.

Komga has a flexible Author-Role structure that could be modified slightly store that kind of Information (not the sidebar location though).

Is your request only about cover details?

**Comment by cesalo** [comment]
Yes, it's coming from comicinfo.xml. If this could be stored within Komga I think it would be great along with the rest of metadata in the xml.
