### ISSUE TITLE
[Feature Request] Thumbnails aspect ratio / fitting

### ISSUE THREAD

**Issue by cesalo** [gotson/komga#191]
### Is your feature request related to a problem? Please describe.
I noticed that in Komga some of the Thumbnails were a little bit closer to the edges than in the other app I use for comics Ubooquity. Never payed to much attention but in a recent series I added it kind of look bad and was almost cutting the title in the thumbnail - This is how it looks in Komga:

![Screenshot from 2020-06-07 16-28-26](https://user-images.githubusercontent.com/16859916/83980347-f1bd1f00-a8e2-11ea-8038-e62cc2694e95.png)

This is how the same series looks in Ubooquity:

![Screenshot from 2020-06-07 17-20-30](https://user-images.githubusercontent.com/16859916/83980377-38127e00-a8e3-11ea-9500-c63867aea996.png)

It seems in Komga the Thumbnails are a bit more zoomed in.

Couple more examples:

**Komga:**

![Screenshot from 2020-06-07 17-23-31](https://user-images.githubusercontent.com/16859916/83980420-b2430280-a8e3-11ea-885a-757532c45c65.png)

**Ubooquity:**

![Screenshot from 2020-06-07 17-24-55](https://user-images.githubusercontent.com/16859916/83980434-d7377580-a8e3-11ea-8990-2b22fb737b1b.png)

### Describe the solution you'd like
I'd like the Thumbnail to show more of the cover and be more zoomed out like in the examples I put from Ubooquity - maybe this was done by design so I didn't add it as a BUG.

### Additional context

An additional issue is when comics have covers in landscape mode.

**Komga version:**

![Screenshot from 2020-06-07 17-27-58](https://user-images.githubusercontent.com/16859916/83980480-44e3a180-a8e4-11ea-91b7-fddb9c64e8da.png)

**Ubooquity version:**

![Screenshot from 2020-06-07 17-28-43](https://user-images.githubusercontent.com/16859916/83980489-5af16200-a8e4-11ea-8751-9f6e874ae165.png)

It would be great if Komga could adapt to Landscape covers.

**Comment by gotson** [comment]
The thumbnail size is fixed. The problem is then: how to fit various size of images into a fixed size rectangle, showing something nice, without empty borders ?

That's what Komga does currently, it fits the image to the target rectangle.

The problem with the landscape covers you show is that it breaks layout. Layout needs to be predictable, whatever the image size.

For your other covers, they are rectangular, but not with the same aspect ratio as Komga, that's why there is some cropping involved on some borders.

Another way to fit would be to stretch, but that's not very nice to the eye.

The curent aspect ratio of Komga's thumbnails is 210x297 (an A4 sheet of paper).

**Comment by gotson** [comment]
I tried a quick test, since the Vuetify Image component has a `contain` attribute to prevent cropping.

Current:
![2020-06-08 10_50_22-Start](https://user-images.githubusercontent.com/2139133/83988533-1adabf80-a976-11ea-892a-393ca9456ccb.png)


With `contain`:

![2020-06-08 10_49_56-Start](https://user-images.githubusercontent.com/2139133/83988542-1dd5b000-a976-11ea-8737-ed6c52104c51.png)

**Comment by cesalo** [comment]
That looks much much better .. :) :).

**Comment by cesalo** [comment]
Interesting to note that almost every comic I have (Image, DC, Marvel) have a size ratio of ~0.65: 1988x3056 - I just opened like 10 cbz - 210x297 is ~0.7. I think that difference is causing the small size issue but as you said it needs to fit everything. Just found curious that all my comics had a different size ratio .. I assume Mangas are 0.7?.

**Comment by gotson** [comment]
Komga was based on French comics, which is 210:297
