### ISSUE TITLE
[Feature Request] Pagination for collections

### ISSUE THREAD

**Issue by mihailim** [gotson/komga#216]
### Is your feature request related to a problem? Please describe.

Now that collections are available (#30), it would be useful to have pagination support for them, similar to how series are paginated, and for the exact same reasons pagination became necessary for series -- first and foremost, web client rendering resource usage.

### Additional context

It might be useful to take this into account for the filtering implementation in the Tachiyomi extension, to avoid having to bolt it on later.

**Comment by gotson** [comment]
For which view would that be, browsing all collections, or browsing a single collection?

**Comment by mihailim** [comment]
Ah, good point, sorry. In my use case, it would be browsing all collections, i.e. `/libraries/<LIBID>/collections` -- at 300+ it already slows down a bit. Didn't think about `/collections/<COLLID>` but I'd expect that one to run into resource limitations for some people in case they'd want to create something like publisher catalog collections.

**Comment by gotson** [comment]
Thanks for clarifying.

I was asking because browsing single collection is tightly linked to reordering items in that collection (well, at the moment it is), so changing to a paginated view would be complex. 

Fair enough for the all collections view, it makes sense. I didn't do it from the beginning for a few reasons (getting all collections for Tachiyomi filtering being one). I would need to find a good way to structure the api to do both. 

And congrats on creating 300+ collections overnight since the release!

**Comment by mihailim** [comment]
Makes sense! Thank you.

Teehee -- it just so happened that I had everything already set up via ComicInfo.xml metadata and was _already_ using SeriesGroup to provide the required info (separated by commas which is suboptimal, but ah well...) so it was trivial to extract everything and set them up in bulk.

**Comment by gotson** [comment]
There's a new virtual scroll component in the latest Vuetify release, if it works well it could remove the need for pagination.

I'll need to upgrade and give it a try. 

It still makes sense to keep the API pageable, but requesting unpaged content should be possible.
