### ISSUE TITLE
[QA] Disable Scan?

### ISSUE THREAD

**Issue by gerroon** [gotson/komga#249]
Hi

I cant access the DIscord channel since it is blocked in the network, so I have to post it here. 

Is it possible to disable the auto sccna and trigger scans only with some cron jobs or regular manual intervals?

**Comment by gotson** [comment]
The automatic scan is a cron job inside Komga, see [here](https://komga.org/installation/configuration.html#komga-libraries-scan-cron-komga-libraries-scan-cron-cron).

You can disable it by using the special value `-`.

> Is it possible to disable the auto sccna and trigger scans only with some cron jobs or regular manual intervals?

I don't quite understand what you are trying to achieve here. Cron jobs is what is used now. Regular manual intervals is not very clear, since _manual_ means triggered by someone, and _regular_ would mean triggered by a scheduler.

What you can do is trigger it from outisde Komga, using the REST API. Check the [demo's swagger](https://demo.komga.org/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/library-controller/scan).

**Comment by gerroon** [comment]
Hi

Thanks for the reply. I am glad that it is possible to do but I do not quite understand where I do change that value (am not a dev)? I am using the compose install.

I am ok with a cron job, I just wnt to change the frequency of it, I have alot of books in the libraries and the scan regularly hogs my computer. So i want something like every 8 hours maybe.

Do I define it like this in the compose file?
```
environment:
      - KOMGA_LIBRARIES_SCAN_DIRECTORY_EXCLUSIONS=#recycle,@eaDir
      -KOMGA_LIBRARIES_SCAN_CRON = 15 */8 * * *
      - JVM_OPTS=-Xmx2g -Xms2g
```


thanks

**Comment by gotson** [comment]
Every 8 hours would be `0 0 */8 * * ? `
