### ISSUE TITLE
Read progress

### ISSUE THREAD

**Issue by gotson** [gotson/komga#25]
Manage read progress per user for books.

Should implement the following features:

- [x] manually mark a book or multiple books as read/unread
- [x] manually mark a series or multiple series as read/unread (would change the status for all books in the series)
- [x] ability to store progress by page per book per user
- [x] [api] read status search criteria for books
- [x] [webui] filter books by read status
- [x] [api] read status search criteria for series (with at least one book matching the criteria)
- [x] [webui] filter series by read status
- [x] add read progress in books retrieved by api (number of page read)
- [x] add read progress in series retrieved by api (count of read, unread and in progress books)
- [ ] ~~[opds] add views for unread series and books~~
- [x] adjust read progress if necessary when a file has changed, and has a different number of pages than previously

**Comment by BloodyIron** [comment]
I'm interested in this too please! \o/

**Comment by anderaith** [comment]
I'm very interrested in this.
The missing functionnality for me is a way to recognize chapters I already read from the unread ones (Big mangas with lots of chapters).
Minimum to be useful would be a way to manually mark them as read. Full functionnality would be something that mark them as read if I saw the last page of an issue.

**Comment by gerroon** [comment]
Does this issue includes remembering the page numbers per book? I am not sure if `storing page progress` is the same thing

**Comment by gotson** [comment]
Yes that's the plan.

However I'm not sure how to mark a page read, once you reach it, or once you reach the one after? 

Corner cases :
- let's say we mark any page that is open : you open a book, you're on page 1. You don't want to mark it as in progress in page 1 if you close it now.
- let's say we mark any page before the current page open as read : you reach the last page of a book, there is no page after. It should still be marked completely read, but it mark progress at the before last page instead.

I think it will need to treat first and last with extra care.

**Comment by gerroon** [comment]
Personally I am happy with anything regarding this issue. It would be so awesome if book page numbers are remembered this way or that way because trying to do this mentally is a bit not possible when browsing or reading through many books.


How about adding a manual bookmark method like reading a physical bookmark?

**Comment by gotson** [comment]
> How about adding a manual bookmark method like reading a physical bookmark?

Haven't thought of that, not sure it would be easy to use. Marking the max of last page read seem easier, but we'll see when we start implementing the feature!

**Comment by GlassedSilver** [comment]
> 
> 
> Yes that's the plan.
> 
> However I'm not sure how to mark a page read, once you reach it, or once you reach the one after?
> 
> Corner cases :
> 
>     * let's say we mark any page that is open : you open a book, you're on page 1. You don't want to mark it as in progress in page 1 if you close it now.
> 
>     * let's say we mark any page before the current page open as read : you reach the last page of a book, there is no page after. It should still be marked completely read, but it mark progress at the before last page instead.
> 
> 
> I think it will need to treat first and last with extra care.

Mark read after n seconds, done. :) 



> 
> 
> Personally I am happy with anything regarding this issue. It would be so awesome if book page numbers are remembered this way or that way because trying to do this mentally is a bit not possible when browsing or reading through many books.
> 
> How about adding a manual bookmark method like reading a physical bookmark?

Hmm... I don't really stop mid-chapters, but when I do it's because I fall asleep, get off a train or some other unexpected event... The kinds of scenarios where general interaction with the device is interrupted.

> 
> 
> > How about adding a manual bookmark method like reading a physical bookmark?
> 
> Haven't thought of that, not sure it would be easy to use. Marking the max of last page read seem easier, but we'll see when we start implementing the feature!

To quote a beatiful meme: Why not both? Because they can serve vastly different use cases...

Like... favorite parts of the story or pages with amazing art. Right now what I do is always screenshotting them... That gets weird and wonky fast...

For read progress however it's automatic or bust.

If someone however prefers to manually set a bookmark and not use or care for the auto-set-as-read feature that's just another personal preference and workflow. :) imho good applications should try to cover multiple workflows, because people are very different. :)
