### ISSUE TITLE
[Bug] General feedback

### ISSUE THREAD

**Issue by disklosr** [gotson/komga#295]
### Komga environment
- **OS**: 
- **Komga version**: 
- [X] **I am running Komga with Docker**
  - Docker image tag: latest 
- [ ] **I am running Komga from the `jar`**
  - Java version: 
- [X] **I have a problem in the web interface**
  - Browser (with version): Firefox 79.0 (64-bit) for Manjaro Linux 
- [ ] **I have a problem with an OPDS client application**
  - OPDS Application (with version): 
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: 
  - Tachiyomi extension version: 

### Describe the bug
Sorry for this low quality issue but I wanted to share my feedback on the problems I encountered when self-hosting Komga.
- Run as a container, Komga consumes over 900 Mb of memory which is not only huge but it prevents people from self-hosting in low end servers having only 512 of RAM.
- I tried using Komga as online pdf reader for reading my books. I enjoyed the experience of reading using the integrated PDF reader, until I had annoying text rendering issues for some of my books. Also, the reader does not allow for text selection, which to me is important for taking notes.

**Comment by gotson** [comment]
> Run as a container, Komga consumes over 900 Mb of memory which is not only huge but it prevents people from self-hosting in low end servers having only 512 of RAM.

Komga is built in Kotlin and run on the JVM, which is known to be more memory hungry than native processes. However the figure presented by the OS is not always relevant to profile a JVM application, as the JVM reserve some memory, but could give it back when needed. You really need to worry when processes exhaust memory, thus crashing, or when there is a lot of swap.

Check #17 for more details on that topic. You can also check the [documentation](https://komga.org/installation/docker.html#increase-memory-limit) on how to limit the memory. Some people run it on low-end Raspberry-PI, and it can run with as low as 200-300MB.

IMHO, servers with less RAM than your average mobile phone shouldn't be a thing in 2020.

---

> until I had annoying text rendering issues for some of my books. Also, the reader does not allow for text selection, which to me is important for taking notes.

Komga is made for comics, not books (see #221). As such, it deals with images, not text. The PDFs are rendered, meaning converted to an image, for display. That's why the text is not selectable.

Regarding the rendering issue, Komga uses the Apache PDFBox library, which sometimes have some issues with particular files. If you have specific cases, feel free to open an issue here, providing the original file, along with screenshots of the rendering in Komga, and the rendering in another PDF tool. I'll happily lodge a ticket at the PDFBox issue tracker, so they can enhance their library.
