### ISSUE TITLE
[Bug] Weird date changing behaviour

### ISSUE THREAD

**Issue by Vodes** [gotson/komga#344]
### Komga environment
- **OS**: Ubuntu 18.04
- **Komga version**: 0.63.2
- [ ] **I am running Komga from the `jar`**
  - Java version: OpenJDK 1.8.0_265
- [ ] **I have a problem with the Tachiyomi extension**
  - Tachiyomi version: Tachiyomi J2k 1.0.9 (latest)
  - Tachiyomi extension version: 1.2.17

### Describe the bug
When adding a new book to a series, Komga seems to update the metadata for all books in that series, setting the last modified to whenever that new book was added.

### Steps to reproduce
1. Have a series with a few books
2. Look at the times that Tachiyomi shows
3. Add a new book to that series
4. 2 again, the times have been reset

### Expected behavior
The older books keep their real date

### Actual behavior
All books now say x hours ago (when you added the new book)

### Screenshots
![Screenshot_20201021-123956](https://user-images.githubusercontent.com/48185123/96710938-0d5e2900-139d-11eb-9f88-3ccff16fb7dd.png)

### Log file
https://gist.github.com/Vodes/325c9dc23eacd106395964e72974c85a

**Comment by gotson** [comment]
> The older books keep their real date

Real date doesn't mean anything, this is not explicit enough.

---

To give you some context on what happens:
- Tachiyomi has a field called `date_upload`. This can be interpreted in many ways, the way the Komga extension fills this field is by using the `book.lastModified` field, which is an internal Komga field that keeps track of the last time the entry in the database has been modified.
- When you add a new file in a folder, and a scan happens, Komga will _sort_ books in the series, to ensure the numbering is correct. For example if you only had issue number 2, it would be called '1' in Komga. If you add issue 1, the renumbering happens, and 1 becomes '1', and 2 changes from '1' to '2'. When that happens, the entries in database are modified to reflect those changes, hence the `book.lastModified` field changes.

That's why you see the date always updated.

Now back to the original point:
- we don't want the date to always change
- we want to use a date that makes sense in that context

I think it would make sense to use `book.fileLastModified`, which is the date coming from the filesystem, not Komga related.

**Comment by Vodes** [comment]
Ah that clears things up. Thanks. Can I expect the changes in an extention update?

**Comment by gotson** [comment]
I'll try to do that when time allows.

**Comment by Vodes** [comment]
Well, the value is already implemented in the extension as far as i can tell so it should be a simple thing

**Comment by gotson** [comment]
Just realized it would be better to use the metadata release date if it exists, and fall back on the file last modified date.

**Comment by gotson** [comment]
Closed in favor of https://github.com/inorichi/tachiyomi-extensions/pull/4682
