### ISSUE TITLE
[Feature Request] have a report on server settings of the current task/scan status

### ISSUE THREAD

**Issue by Tonic8** [gotson/komga#361]
### Is your feature request related to a problem? Please describe.
When onboarding set of comics, they appear immediately (without cover), but in the background the scan start and can take time.
I can see the actual tasks only on komga logs

### Describe the solution you'd like
have on the libraies tabs near the number of comics the number of comics not yet scanned

### Describe alternatives you've considered or other apps that can do what you want
no idea about another software doing it

### Additional context
one other way is also maybe to have a webui option to show only comics scanned and hide the not yet scanned comics

![image](https://user-images.githubusercontent.com/18634390/102117148-42877480-3e3e-11eb-8665-90cf14b9930b.png)

**Comment by gotson** [comment]
You confuse scanned and analyzed. Books not scanned are unknown to Komga:
- Books scanned but not analyzed will show in the ui without cover and without number of pages.
- Once analyzed, you will see the number of pages, and file type.
- Once cover is generated you will see it. 
- Then metadata is refreshed and you will see additional information of you have any for that book, as well as custom cover.

Books already have a status which can be used to filter via the api, but it's not used on the ui. It's used in Tachiyomi to only show books that are analyzed (ready state) so that tachiyomi doesn't cache not ready books, which causes problems afterwards.

I have plans to add feedback in the ui of what's happening on server side (#124). This should also trigger some refresh on the ui to update books once they are ready for example.

**Comment by Tonic8** [comment]
thanks for the clarification between scanned and analysed.
i was effectively confused.
