### ISSUE TITLE
[Feature Request] Support for Perfect Viewer (Android App)

### ISSUE THREAD

**Issue by SonOfDiablo** [gotson/komga#365]
Hello,

Would it be possible to provide a plugin for [Perfect Viewer](https://play.google.com/store/apps/details?id=com.rookiestudio.perfectviewer&hl=en&gl=US)? 

I read you already have support for [Tachiyomi](https://www.reddit.com/r/sonarr/comments/dingyp/is_there_an_equivalent_of_sonarrradarr_for_comics/f44z0v3/), however I (personally) like Perfect Viewer better.

I haven't looked into what it actually takes to write a Perfect Viewer plugin, but I know the app does support plugins (Thought not sure if it actually has support for library Plugins)

**Comment by gotson** [comment]
From a quick look it supports opds, you could try that.

I have no interest nor time to develop something for that app. Komga has an open REST api that anyone can use, and also has opds which is a widespread standard.

I developped the Tachiyomi plugin not because I develop Komga, but because I use Tachiyomi.
