### ISSUE TITLE
Read Information in ComicInfo.xml format from external file

### ISSUE THREAD

**Issue by MKH-42** [gotson/komga#408]
### Is your feature request related to a problem? Please describe.
I want to store my Information in ComicInfo.xml format like it is possible in plex or emby to safe the information in a seperate file.

### Describe the solution you'd like
It would be fantastic to store the data in the same directory as the comic only with the ending xml instead of cbr/cbz/..
Example:
I have a comic with name mycomic.cbr in the directory c:\comics.
I want to store a file in ComicInfo structure with the nme mycomic.xml in c:\comics.
So I have now 2 files in c:\comics:
mycomic.cbr
mycomic.xml

Komga shout look first in the mycomic.cbr for a ComicInfo.xml and than check a file named mycomic.xml in the same directory.
Sequence should be: Outside xml has a higher priority than the internal ComicInfo.xml file.

### Describe alternatives you've considered or other apps that can do what you want
Mybe we can use instead of mycomic.xml also mycomic.info

### Additional context
For my understanding everything to implement this feature should be availabe.
Komga already read the ComicInfo.xml structure from the comic book.

**Comment by MKH-42** [comment]
*push*

**Comment by gardn701** [comment]
I would also support a feature that doesn't change the source files (particularly file hashes).  If you could integrate some sort of metadata tagging into konga that stores all that information in it's own database like Plex does, as stated above, that would be the ideal solution.

**Comment by MKH-42** [comment]
Please don't close it :-)

**Comment by kimhomo** [comment]
+1

**Comment by Maltavius** [comment]
Yeah me too, I don't want to taint my files with Comicrack writing information to them and I've thus used the ExportComicInfoToXML plugin for Comicrack.
It creates a file with the same name as the comic in the same folder as the comic the only difference is the extension is xml.
Read that instead of trying to find a ComicInfo.xml inside the file please.

The file starts like this (I've removed the < > since the lines didn't show up if I had them there:


?xml version="1.0"?
ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  <Title>Book One</Title>

**Comment by 08shiro80** [comment]
please up, its better as to extra add the comicinfo.xml in on chapter if they are all in one folder anyway

**Comment by Cwavs** [comment]
+1 for this, I have some manga only in PDF because Kodansha decided to just not provide CBZs for them in their latest bundle, and afaict ComicRack cannot write metadata to PDFs, and even if it could the Komga docs don't seem to indicate that Komga could read the metadata from it. As such it would be nice to have the option to import an external comicinfo.xml file in someway, as currently my only other real option is to run through and manually add the metadata myself. Thanks for your hard work on Komga.

**Comment by nhysteric** [comment]
+1
I use my own crawler to get matadata from web, so I need to recompress ComicInfo.xml to the .cbz. It's totally inefficient.
As for series.json, it has stricter requirements on fields, and it doesn't use [tags] field, which is important to me

**Comment by chooban** [comment]
I was giving this some thought as a potential first issue for me (like I'll ever find time...). I think that Komga now imports files with the same name as a comic file but a different extension, known as sidecars, is that right? If so, would that bring in a suitably named XML file? Maybe at that point, whereever the "get comicinfo.xml" function that presumably looks inside a CBZ could also be updated to check for files on the filesystem.

**Comment by alehel** [comment]
I'd certainly appreciate support for comic-info.xml files as sidecar files. For instance 
```
-Top Cow
  |-Tomb Raider (1999-2005)
    |-Tomb Raider (1999-2005) #1 - The Medusa Mask part1.cbz
    |-Tomb Raider (1999-2005) #1 - The Medusa Mask part1.xml
    |-Tomb Raider (1999-2005) #2 - The Medusa Mask part2.cbz
    |-Tomb Raider (1999-2005) #2 - The Medusa Mask part2.xml
```

Advantages: 
- comic-info.xml can be used with any file: pdf, cbz, epub, etc.
- no need to modify your comic files when introducing/editing metadata.

**Comment by neta540** [comment]
+1

**Comment by Suwmlee** [comment]
+1 

like movie nfo file

would be a huge improvement
