### ISSUE TITLE
[Feature Request] Add additional Reading mode (Vertical + Webtoon)

### ISSUE THREAD

**Issue by vegedb** [gotson/komga#427]
Webtoon is excellent for Manhwa since it doesn't have gaps in between chapters.

For manga and comics, there is a separation between chapters.

### In between chapters
![image](https://user-images.githubusercontent.com/72070424/109128366-621a1200-778a-11eb-8960-2ecc95222f10.png)

Could you add an option that is in between **_Vertical_ & _Webtoon_** that has gaps in between chapters for some separation. 

### EXAMPLE (Tachiyomi Continuous Vertical) 

![image](https://user-images.githubusercontent.com/72070424/109129303-74e11680-778b-11eb-9ade-c101cb6c3ef2.png)

**Comment by gotson** [comment]
When you say chapters, you mean images ? Like some gap between each image?

**Comment by vegedb** [comment]
Yup the images. Add the gap to the webreader would be great. Perhaps another mode like tachiyomi called **Continuous Vertical**

**Comment by gotson** [comment]
Or just add an option for the gap size in webtoon?

**Comment by vegedb** [comment]
> Or just add an option for the gap size in webtoon?

A second "webtoon" with option with gap size would be excellent!
So there will be 2 webtoon options.

**Comment by gotson** [comment]
Just the same way you can adjust side padding, we could adjust gap between images.

**Comment by vegedb** [comment]
>Just the same way you can adjust side padding, we could adjust gap between images.

Please add a 4th option for that and don't touch the current webtoon.

I have mixed content and changing padding every time I want to revert it would not be productive.

**Comment by gotson** [comment]
I don't plan on adding a new reading direction in series metadata.

**Comment by gotson** [comment]
> I have mixed content and changing padding every time I want to revert it would not be productive.

If i understand correctly, at the moment you set the reading direction in the series metadata to `Webtoon`. It seems you are assuming that a new reading direction would be needed to persist reader settings.

I don't want to add another reading direction in the series metadata, because that's not really metadata, but reading preferences, and as such are individual preferences, not absolute. We can tell in an absolute manner whether a book is to be read in LTR, RTL, Vertical or Webtoon. Whether it should display with side padding, gap between images, double pages or single pages, is all a matter of personal preferences, and device preferences.

What I would prefer to do is:
- add a `Gap between images` option in the Webtoon reader
- make the settings of the webreader stick to the series+device, instead of device only

That way you could change a series to Webtoon with image gaps, and another series to Webtoon without gap, and the settings would be kept.

**Comment by vegedb** [comment]
>make the settings of the webreader stick to the series+device, instead of device only

This is an awesome idea! 

The only thing I like about webtoon, it doesn't mess up when zoom in browser is used. Maybe that's for another request. The other modes are persistent when you ctrl+scroll wheel. It doesn't zoom the comic, rather it zooms the UI and web interface which i always found infuriating. Luckily webtoon saved the day! Tested in chrome/firefox.
