### ISSUE TITLE
[Bug] Scanner performance degraded since 0.63.3

### ISSUE THREAD

**Issue by xx255q** [gotson/komga#443]
### Komga environment
- **OS**: 
- Windows 10 latest
- **Komga version**: 
- 75.2
- [ ] **I am running Komga from the `jar`**
  - Java version: 
  - Java 8 Update 261

### Describe the bug
For the last serval versions dating back a number of weeks now the rate of which Komga scans has slowed from minutes to hours. Also when this issues started the drive in which it the comics/manga are located now is always being used 65-90%
### Steps to reproduce
As soon as you run it the effects start and don't stop

### Expected behavior
The drives would mostly now be active like how it was in earlier versions 

### Actual behavior
What happened instead.

### Log file
If applicable, add an excerpt of the log file (max 20 lines), or a link to a gist containing the log file.
I will provide logs if told pathway to reach them

**Comment by gotson** [comment]
Logs are inside your user directory in a folder name `.komga`

**Comment by xx255q** [comment]
[komga.log](https://github.com/gotson/komga/files/6094546/komga.log)
Here it is

**Comment by gotson** [comment]
Can you provide information about your hardware, disk setup, filesystem, is it a local storage or remote storage, and for your libraries the number of files and total size?

I see you have a manga library with 120k files, which takes 75 minutes to scan.

**Comment by xx255q** [comment]
Sure thing but no hardware or overall size of library changed between the issues I have now and when it was working better before:


It is run from an NTFS drive HDD at 7200rpm and the drive holding the files is also NTFS but is an usb external at 5400rpm so both drives are local. my overall system is an i5-8400 with 16gb of ram.

For my library size it is 1.58TB with 212,073 files 15,007 folders

**Comment by gotson** [comment]
Usb is not local, probably slower than a sata drive, especially à 5400.

I suggest you reduce the frequency of the scans. By default it runs every 15mn, and since your large library takes 80 minutes to scan, once it finishes it will scan again. 

> Sure thing but no hardware or overall size of library changed between the issues I have now and when it was working better before

Can you clarify what you mean by "when it was working better before"? What does "working better" mean and when was "before"?

**Comment by gotson** [comment]
Also, is it a USB 2 or 3?

**Comment by xx255q** [comment]
What I meant was it had only taking minutes for a new issue to show up as I already wrote in the initial post. As for how long it has been about 5-6 weeks either version 69.1 or 63.2. I just ran 63.2 and the difference in drive usage is clear, with this older version you are getting spikes when the writing of new issues to the drive but thats all those are, spikes. There are even times it hits 0 instead of the 65-90% that new versions are always having on the drive. For a test I downloaded a new series at 8:45, at 9:00 I assume the scan started by the drive being maxed out to 95-100% and lasted for 2 minutes after which the series now showed up. As for the drive usage it went back to spikes or hardly any usage. I dont know what changed for for me this is working far better

**Comment by xx255q** [comment]
Also is it possible to adjust the time it scans to 5 or 10 minutes?

**Comment by gotson** [comment]
> Also is it possible to adjust the time it scans to 5 or 10 minutes?

You mean the frequency? If yes, yes. Check the docs it's explained.

**Comment by gotson** [comment]
> What I meant was it had only taking minutes for a new issue to show up as I already wrote in the initial post. As for how long it has been about 5-6 weeks either version 69.1 or 63.2. I just ran 63.2 and the difference in drive usage is clear, with this older version you are getting spikes when the writing of new issues to the drive but thats all those are, spikes. There are even times it hits 0 instead of the 65-90% that new versions are always having on the drive. For a test I downloaded a new series at 8:45, at 9:00 I assume the scan started by the drive being maxed out to 95-100% and lasted for 2 minutes after which the series now showed up. As for the drive usage it went back to spikes or hardly any usage. I dont know what changed for for me this is working far better

Can you provide log files of 63.2?

**Comment by xx255q** [comment]
[komga.log](https://github.com/gotson/komga/files/6096436/komga.log)
Is this what your looking for?

**Comment by gotson** [comment]
Thanks a lot, that's very helpful.

In `0.63.3` the scanner was changed to accommodate issues with files that could not be accessed because of access rights, which would crash the scanner.

https://github.com/gotson/komga/commit/f43a3864f869d254e75b18c00c4a1585ed69fd25

This seems to have degraded the performances for you. I asked a couple of people with 1TB+ libraries and they have the same performances as before.

Do you have some directories with lots of files? Like 10000?

**Comment by xx255q** [comment]
My file structure is  Main folder - Series - issues as for the largest single amount of files maybe a little over 1000 for one piece. I don't believe I have a series with 10000+ files. Is it possible to have an option for scanner? due to the updates Tachiyomi only really works for the newest versions of Komga

**Comment by xx255q** [comment]
My main Comic folder is 212,000 files with 15000 folders

**Comment by gotson** [comment]
I will try to look at this, I need to reproduce the issue and find a way to get a faster scanner that also handles files that cannot be accessed.

For tachiyomi you should be able to install the older version of the extension from https://github.com/tachiyomiorg/tachiyomi-extensions/tree/repo/apk

It would need a bit of digging as the branch is updated with only the latest version of each extension, but going through the got history you should be able to find an extension compatible with 0.63.2. Ask on Tachiyomi's Discord server for help if needed.

**Comment by gotson** [comment]
Could you try [this](https://www.dropbox.com/s/bk8ndtznvzwyhc5/komga-0.77.1.jar?dl=0) `jar`? I don't think it would solve the issue, but it's worth a try.

I couldn't reproduce the issue locally. I can reproduce some very long scan time, but the old 'faster' version is running at the same speed as the current 'slow' version in my tests, so it's not accurate.

Given i don't have access to a Windows machine nor NTFS file system, I think the best is for me to provide you with some custom builds until we can match the previous performance.

In order to test it, you can:
- stop Komga
- rename or delete the log file (so i can get a clean log file with only the relevant log)
- start the new `jar`
- manually start a scan of your biggest library (`Manga` i think)
- attach the log file once done

**Comment by xx255q** [comment]
Did not get a chance to manually scan after i started to download a new series the drive is now already constant in use. Also in tachiyomi the latest button no longer works and how do I get back latest updated series in Komga?
[komga.log](https://github.com/gotson/komga/files/6097276/komga.log)

**Comment by gotson** [comment]
> Also in tachiyomi the latest button no longer works and how do I get back latest updated series in Komga?

I think you may have added/updated series while running the previous `0.63.2` version. This is not a good idea, as the database schema has evolved and the data is not compatible anymore.

To fix it easily, I would suggest that you remove or rename the series that were updated recently, and run a scan. The scan will delete/update those series, and fix the database issue.

**Comment by gotson** [comment]
Could you give a try to this [new](https://www.dropbox.com/s/rj5500ynzpe7ncz/komga-0.77.3.jar?dl=0) `jar` ?

**Comment by gotson** [comment]
> > Also in tachiyomi the latest button no longer works and how do I get back latest updated series in Komga?
> 
> I think you may have added/updated series while running the previous `0.63.2` version. This is not a good idea, as the database schema has evolved and the data is not compatible anymore.
> 
> To fix it easily, I would suggest that you remove or rename the series that were updated recently, and run a scan. The scan will delete/update those series, and fix the database issue.

You could also try to do a **Refresh metadata** on the recently added series, that could work.

**Comment by xx255q** [comment]
As soon as I started the new jar I get the constant usage. Also I noticed my database.sqlite file is 5gb, I dont remember if it was always that large
[komga.log](https://github.com/gotson/komga/files/6101396/komga.log)

**Comment by gotson** [comment]
That log is not enough, you need to run it for some time so I get enough logs. Thanks.

**Comment by xx255q** [comment]
[komga.log](https://github.com/gotson/komga/files/6104344/komga.log)

**Comment by gotson** [comment]
Thanks, no luck with that method either. Just so i'm not going crazy, could you give a try to [this one](https://www.dropbox.com/s/wipsasafoyuuvtl/komga-0.77.3-originalwalk.jar?dl=0) ?

It's the latest version, but with the older method of walking the file tree.

**Comment by xx255q** [comment]
No change, still in constant use

[komga.log](https://github.com/gotson/komga/files/6108508/komga.log)

I know you most likely but here is what i got so far

**Comment by gotson** [comment]
> No change, still in constant use
> 
> [komga.log](https://github.com/gotson/komga/files/6108508/komga.log)
> 
> I know you most likely but here is what i got so far

That's weird, if you can post logs after a while that would help. It's the same code as in `0.63.2`, but if you don't get the same performance then the problem must lie elsewhere...

**Comment by gotson** [comment]
Could you also try to install adoptopenjdk 11 and see if there's any difference?

**Comment by xx255q** [comment]
[komga.log](https://github.com/gotson/komga/files/6109253/komga.log)
as for 9:45am

**Comment by xx255q** [comment]
First thing I notice is the constant use issue is still there but even greater, it is now always maxed at 97-100% will give logs later

**Comment by xx255q** [comment]
[komga.log](https://github.com/gotson/komga/files/6119051/komga.log)

**Comment by xx255q** [comment]
I also just noticed now that was no drive activity, when downloading new series then there is activity then drops off when downloading complete. In Tachiyomi the latest button does not working giving an error 500. In the web view the latest updated series list is gone, was it removed?

**Comment by xx255q** [comment]
Another update: The recently updated series bar/list has now appeared and I assume those are connected because the app latest works now also. So what changed in 79.1?

**Comment by xx255q** [comment]
The recently updated series list/tab is once again missing in the web browser

**Comment by julien-vu** [comment]
If I can add to the topic, the scan library does not work anymore for me on 0.79.1,
Does not recognize new books, and when it displays a new one, got 0 page

**Comment by gotson** [comment]
@xx255q the problem seems fixed:

`2021-03-10 08:30:06.021  INFO 26448 --- [DefaultMessageListenerContainer-1] o.g.k.domain.service.FileSystemScanner   : Scanned 9727 series and 118035 books in 5.27s`

It went down from 80 minutes to 5s.

> In Tachiyomi the latest button does not working giving an error 500. In the web view the latest updated series list is gone, was it removed?

That is because of the series you scanned while running in `0.63.2`, but after you downgraded. The database schema is not compatible, and some data is missing. I already provided the steps to remediate the data above, please check my earlier comments.

> The recently updated series bar/list has now appeared and I assume those are connected because the app latest works now also

It only works because the last 20 series you added/modified do not have problematic data. If you were to retrieve the series with problem, it would fail. That would also happen when browsing. You need to fix the data.

> So what changed in 79.1?

- removed some duplication of file tree exploration
- removed the checks for hidden files. Now it only check for Linux hidden files starting with `.`, which can be done by only looking at the file name, while i suspect on Windows it needs to retrieve file attributes in the filesystem, probably costly.
- removed the checks to see if a file is readable. Unreadable files are returned, but will generate an error during analysis instead.

**Comment by gotson** [comment]
> If I can add to the topic, the scan library does not work anymore for me on 0.79.1,
> Does not recognize new books, and when it displays a new one, got 0 page

Please open a new issue.

**Comment by xx255q** [comment]
The refresh metadata did not work and new comics are no longer showing up and there is a lower constant disk usage. How do I just purge it all. I tried to upload the log file but its growing at an amazing rate currently at 5.8MB in under 20 minutes? and as I write this it is at now 6mb, Had to shut it down and restart and upload the logs before it gets to big to post.

**Comment by xx255q** [comment]
I tried to upload again and it says the log file is unsupported file type, I uploaded it to this web address i googled:

https://cloudvyzor.com/logpad/?query&database=sandbox-d0a725d1ab97d0542216aadb328b54c0

Let me know if that works for you or if you know another site to upload to

**Comment by gotson** [comment]
That's because of the new feature added to import ISBN from barcode.

What you can do to stop it on all your books:
- stop komga
- in the folder where you found the logs, there is a folder called `artemis`. Delete it. It will remove all the pending tasks
- restart komga
- edit your libraries to disable the import from barcode ISBN

That should remove the disk usage, and you should be able to try a metadata refresh on your libraries.
