### ISSUE TITLE
[Feature Request] Display ISBN in readable format

### ISSUE THREAD

**Issue by bdjPenguin** [gotson/komga#467]
It's now possible to store the ISBN of a book.
Unfortunately, the display of the ISBN in the interface 'loses' the readable format.

Example: '978-2-347-04033-5' is displayed (and probably stored) as '9783347040335'.

[isbn standard](https://www.isbn-international.org/content/what-isbn) allows the usage of hyphens and spaces.

**Comment by gotson** [comment]
_Please follow the templates when filling issues._

ISBN are easy to validate without hyphens, however formatting them is complex because it depends on the publishers group list. 

How they are stored is not your concern.

I'll try to find a library that would have up to date groups for hyphenation.

**Comment by bdjPenguin** [comment]
_Sorry for the template, I'll do it better next time_

If we fill the ISBN field with '978-2-347-04033-5', you seem to remove the hyphen.
That would be better if you keep the hyphens to displayed them later.
Introduce:
![image](https://user-images.githubusercontent.com/80747293/111306166-29b67700-8658-11eb-8f79-9c7d30880514.png)
Save
Re-edit:
![image](https://user-images.githubusercontent.com/80747293/111306262-4b176300-8658-11eb-88ef-b14a0517295b.png)
You seem to 'clean' the ISBN before storing it.

**Comment by gotson** [comment]
There's no guarantee than any ISBN will be filled with the proper hyphenation.
