### ISSUE TITLE
Request: Add (tick box) option to enable/disable password change feature for non-administrator users

### ISSUE THREAD

**Issue by whalehub** [gotson/komga#47]
This would be useful for shared accounts to prevent accidentally or intentionally locking other people out by changing the password.

**Comment by gotson** [comment]
Why would you share accounts when everyone can get their own ?

**Comment by whalehub** [comment]
@gotson Well, my use case is sharing my library with several dozen people and it would be easier to have all of these people share one account instead of creating a separate account for each of them.

**Comment by gotson** [comment]
I understand your concern, but i don't want to bend the model because you are lazy creating accounts for everyone :)

Also, the user account will have more meaning than just authentication later on. The first feature coming is read progress (#25), and i'm sure you don't want people to open a book and get in the middle of it because someone else sharing the same account was also reading it.

There will be other features tied to a user account later on also, most probably device management (like Plex does) and activity tracking.

**Comment by gotson** [comment]
If that can help you, you can use the [REST API](https://github.com/gotson/komga#apis) to create user accounts, so you could write a small script to automate creation, or maybe use a tool like Postman if you can't code.

**Comment by whalehub** [comment]
@gotson Thanks, the API will be useful for creating several accounts quickly.

**Comment by gotson** [comment]
I forgot to comment here, but the `demo` profile has been added some time ago, and prevents password modification by users. It's used on the demo website.

**Comment by whalehub** [comment]
@gotson Thank you!

**Comment by MaestroJAL** [comment]
How do we enable the demo profile? I'm using one account for my students and don't want any one of them to change the password for their shared account. For me it doesn't make sense to make an account for all of my students separately. I've been using one account for a month and so far no one has tried to change the password.

**Comment by gotson** [comment]
You can set `spring.profiles.active: demo` in the application.yml, or `SPRING_PROFILES_ACTIVE=demo` via environment variable.

**Comment by MaestroJAL** [comment]
@gotson Thanks, I'll give that a shot.
