### ISSUE TITLE
[Feature Request] bulk edit for book metadata

### ISSUE THREAD

**Issue by xtra-be** [gotson/komga#476]
### Is your feature request related to a problem? Please describe.
when importing multiple items in a series sometimes the numbering is not set correct. 
also sometimes i have multiple versions of the same issue. to 3 versions of the same issue all with same numbering
when editing the metadata i have to open each issue individually and there is no easy way to edit these in bulk of switch fast to the next issue.

### Describe the solution you'd like
i propose 2 solutions, one easy and one more difficult.
easy one : on the edit page present a next button that goes to the next issue in the series
difficult one:
provide a way to edit metadata in bulk. maybe some sort of spreadsheet view?

### Describe alternatives you've considered or other apps that can do what you want
at the moment the only solution i have found is 
press edit
edit the data
save changes
select next issue and repeat the process

**Comment by gotson** [comment]
You can use the quick edit button on the book card:

<img width="681" alt="Screenshot 2021-03-22 at 10 06 58" src="https://user-images.githubusercontent.com/2139133/111931639-91584080-8af6-11eb-9e2e-4fd0d6e0412f.png">

When in a book details page, you can also navigate to the previous/next book using the navigation at the top right:

<img width="144" alt="Screenshot 2021-03-22 at 10 09 06" src="https://user-images.githubusercontent.com/2139133/111931686-b2b92c80-8af6-11eb-9a02-fd85fec7e99e.png">

**Comment by xtra-be** [comment]
hi 
yes this flow work
except when doing this on 300+ issues
this is a lot of clicking and repetitive tasks.

**Comment by gotson** [comment]
If you have mismatched numbers on 300+ issues you probably need to fix your file names more than fixing the metadata directly.

**Comment by painiax** [comment]
Would be interesting for Crossover events

**Comment by gotson** [comment]
> Would be interesting for Crossover events

In what way? Cross-over should be placed in read lists instead, that's the whole purpose.

**Comment by painiax** [comment]
But read lists don't solve the problem. If I have a 004 Iron Man 002 (2020) komga doesn't know what order it should be and it either gives 5 books the number 001 or some random number like 017. So a quick way to sort 50 books would be great

**Comment by gotson** [comment]
> But read lists don't solve the problem. If I have a 004 Iron Man 002 (2020) komga doesn't know what order it should

With Read List you have to give the order you want. You can drag and drop items to place them in the order you wish, while keeping the books in their original series.

> it either gives 5 books the number 001 or some random number like 017.

Komga does not give numbers in read list, it's just a relative order. I think you may be mistakenly looking at the number of the book in the series, and if you get 5 times the number `001` that's probably because of some metadata in your embedded `ComicInfo.xml`, same for your random number.

Have a good read at the documentation to understand how metadata is managed, and what are read lists. They are very different than series.

**Comment by gotson** [comment]
@xtra-be I might be considering a new edit dialog to edit multiple books at the same time, however I don't want to clutter the dialog with too many fields, so I will probably only allow edit for the following fields:
- title
- number
- sort number

The dialog would allow edit of all the selected books. It could be interesting to couple that with #291 to select all books currently displayed on the page, or via a shift click, but that's more complex to implement.

**Comment by Kussie** [comment]
You could also have some of the other fields hidden under a collapsible toggle to edit some other fields like year, publisher, author etc

**Comment by gotson** [comment]
> You could also have some of the other fields hidden under a collapsible toggle to edit some other fields like year, publisher, author etc

Yes. I don't necessarily want this to become a spreadsheet like dialog though. Will need to see how it looks like in a first iteration maybe, and adjust if needed.

**Comment by GlassedSilver** [comment]
> 
> 
> If you have mismatched numbers on 300+ issues you probably need to fix your file names more than fixing the metadata directly.

Having a chapter 0 file for a manga or some extra chapters (e.g. Chapter 20.5) is well enough for this to become an instant issue.

Alternatively parsing the number and sorting number from the file name rather than "n's file in folder" could help against this.



> 
> 
> @xtra-be I might be considering a new edit dialog to edit multiple books at the same time, however I don't want to clutter the dialog with too many fields, so I will probably only allow edit for the following fields:
> 
>     * title
> 
>     * number
> 
>     * sort number
> 
> 
> The dialog would allow edit of all the selected books. It could be interesting to couple that with #291 to select all books currently displayed on the page, or via a shift click, but that's more complex to implement.

I understand that you want to keep it clean and tidy, but I think managing the metadata of hundreds of files shouldn't be more inconvenient because the edit dialogue might look a bit cluttered. If anything adding sections that are collapsible would be a happy middle ground.
