### ISSUE TITLE
Edit metadata manually

### ISSUE THREAD

**Issue by gotson** [gotson/komga#48]
While #11 is tracking a high level need to handle metadata from various sources, this issue will focus on implementing the metadata model and offer manual edition.

### Book metadata fields:

- [x] **Title**
Not all books have names, usually they only have an issue number. However some books do have an explicit name (ex: [Blacksad](https://fr.wikipedia.org/wiki/Blacksad#Albums)).

- [x] **Number**
The issue number within the series.
Will need to accommodate for #43, so probably a `String`. 

- [x] **Summary**

- [x] **Author(s)**
The name of an individual, group or collective that participates in the creative process of an artistic work.
Optionally an author can have one or multiple roles (writer, artist, cover...) for this particular book.

- [x] **Release date**

- [x] **Age rating**
The minimum age rating for this book, like 12+, 17+, 0+.

- [x] **Reading direction**
One of: Left-to-right, Right-to-left, vertical, webtoon

### Series metadata fields:

- [ ] **Publisher**
The publishing company (Marvel, DC, Glenat...)
:warning: Most of the providers will have the publisher set at book level. Given a serie can only have one publisher, there could be a difficulty to reduce the list of publisher from all the books into one. A mitigation would be to have the publisher set at book level, and to perform a simple string concatenation of the distinct publishers for the series publisher.

- [ ] **Genres**
A list of tags like Science-Fiction, Adventure...
This could also be set at book level, but having it in the series makes more sense to me.

- [ ] **Language**

- [x] **Status**
One of: ended, ongoing, abandoned, hiatus.

- [x] **Title / Sort Title**

**Comment by muchtea** [comment]
I have a few suggestions for some more series metadata fields.

- Names should maybe be split into 
  - official names (e.g. japanese: "Yahari Ore no Seishun Love Come wa Machigatteiru", en: "My Youth Romantic Comedy Is Wrong as I Expected"), 
  - short names/abbreviations ("Oregairu"), 
  - and maybe also other alternative names or name spellings, which some series might have.

- Tags
Add tags for characters (e.g. Spiderman) and themes (e.g. violence, swordplay. female protagonist, etc.).

- Two Status-Tags
One for the original Japaneses release of a manga and one for the publish-status of the English publisher, since those two are often not the same, and might remind me to occasionally look for newly translated manga volumes of the series.

- URLs-Field
To put links to retailers, information-sites, twitter of the author, etc. for the series or book.

- Related Series
This would be helpful for books or series which have sequels, prequels, alternative versions or other series in the same comic/manga universe.
