### ISSUE TITLE
[Feature Request] Crop covers to fit the cards

### ISSUE THREAD

**Issue by unfinishedh** [gotson/komga#536]
### Is your feature request related to a problem? Please describe.
It is just a cosmetic issue, but I found that depending on the resolution of my comic books, their cards do not get fully filled with the cover image. Some leave small white rows or columns at the sides so the results, particularly between different series, are visually a bit uneven. 

### Describe the solution you'd like
I'd think it would be nice to get the card completely filled by the cover by slightly cropping the image until reaching the correct aspect ratio for the card.

### Describe alternatives you've considered or other apps that can do what you want
If I am not mistaken, Jellyfin (and probably others) already does something similar with the movie posters.

!example (https://user-images.githubusercontent.com/42492629/118097867-6d7df080-b3fd-11eb-85f7-1865d5a2d8d7.png)

**Comment by gotson** [comment]
The problem is that each publication has a different image ratio for the covers. US Comics, European comics, and Manga all use different ratio.

If we fill the card, then some part is cropped. The cropped part is important for many people, it usually containers the title for example.

It was the case before, but caused problems. See #191
