### ISSUE TITLE
[Feature Request/Unexpected Behavior/UX] Option to not display the order number in the title of the chapter/book

### ISSUE THREAD

**Issue by GlassedSilver** [gotson/komga#561]
### Is your feature request related to a problem? Please describe.
It most definitely is.
I'm using Komga in conjuction with Tachiyomi and I have several manga where there are .5 or a and b chapters.
So whilst technically 3b is the fourth chapter if it is preceeded by 1,2 and 3a it is a bit of a problem to display it as:
"4 - Chapter 3b <Chapter Name>"

Note: I'm using the terminology chapter instead of book here as it is called in Komga itself, but I'm a manga user and hardly have any manga not in a "1 'book' per chapter" format.

The problem is that in Tachiyomi the read status sync will trigger to mark chapter 4 to be set as read on Kitsu, MAL and Co.

This does NOT happen if I sync my progress through the MangaDex favorites. The reason is that the "order number" (idk how to call it, the thing before the dash) is only internal, but not displayed and doesn't get parsed for chapter recognition which apparently picks up the next best number that looks like a chapter number.

Also, it doesn't look very clean...

![image](https://user-images.githubusercontent.com/1912133/123306515-af807300-d521-11eb-9038-8b51335c73df.png)

### Describe the solution you'd like
An option for that number not to be displayed and hence parsed by Tachiyomi for chapter recognition, but also because it's a bit of an eyesore for manga users. ESPECIALLY if you already have the volume displayed there as well.

### Describe alternatives you've considered or other apps that can do what you want
n/a

### Additional context
n/a

**Comment by gotson** [comment]
The name displayed in Tachiyomi is equivalent to the one displayed on the Komga cards: `<metadata.number> - <metadata.title>`.

If you don't have proper metadata, then it will display the default number generated by Komga, which is the index of the file in the folder, and the default title generated by Komga, which is the file name without extension.

The chapter number in Tachiyomi will be set to the metadata sort number.

See how it renders for a series with proper metadata, and with non-linear numbering:
<img width="200" alt="Screenshot 2021-06-25 at 10 14 03" src="https://user-images.githubusercontent.com/2139133/123358384-ff048480-d59d-11eb-98a7-dbeda0251218.jpg"> <img width="200" alt="Screenshot 2021-06-25 at 10 14 03" src="https://user-images.githubusercontent.com/2139133/123358388-0330a200-d59e-11eb-9c5b-5f37084fd9bf.jpg">

And the equivalent Komga view:
<img width="1118" alt="Screenshot 2021-06-25 at 10 14 03" src="https://user-images.githubusercontent.com/2139133/123358464-1ba0bc80-d59e-11eb-930e-eb13255c9341.png">



> So whilst technically 3b is the fourth chapter if it is preceeded by 1,2 and 3a it is a bit of a problem to display it as:
> "4 - Chapter 3b "

You probably need to update the metadata in Komga to change the `number` of those chapters to something like `3a`, `3b`.

> The problem is that in Tachiyomi the read status sync will trigger to mark chapter 4 to be set as read on Kitsu, MAL and Co.

That's because your Number Sort is not set, so the chapter number in Tachiyomi is incorrect.

> This does NOT happen if I sync my progress through the MangaDex favorites.

I have no idea what that is 🤷🏻 

> Also, it doesn't look very clean...

I looks the same as Komga.
