### ISSUE TITLE
Use StoryArcNumber from ComicInfo.xml

### ISSUE THREAD

**Issue by gotson** [gotson/komga#573]
Since Mylar added this, we should use it if present to position the book in the read list.

**Comment by GiscardBiamby** [comment]
This doesn't seem to work, or I might not understand how to use it with reading lists that were set up prior to the 0.108 release. I'm on 0.108.0 and  my .cbz files have StoryArcNumber inside ComicInfo.xml but the order of the reading list in Komga goes by the issue number, not the StoryArcNumber. I tried refreshing metadata for all the issues in the read list but the order still  goes by issue number.

**Comment by gotson** [comment]
> This doesn't seem to work, or I might not understand how to use it with reading lists that were set up prior to the 0.108 release. I'm on 0.108.0 and my .cbz files have StoryArcNumber inside ComicInfo.xml but the order of the reading list in Komga goes by the issue number, not the StoryArcNumber. I tried refreshing metadata for all the issues in the read list but the order still goes by issue number.

If the book is already in the read list, it won't be added again on metadata refresh. Delete the list, or remove the book from hit, then refresh metadata.

**Comment by GiscardBiamby** [comment]
I can try that. If I delete the list, how do I get komga to regenerate it? When I click delete it warms me that the deletion is irreversible so I hadn't tried that yet.

**Comment by gotson** [comment]
> I can try that. If I delete the list, how do I get komga to regenerate it? When I click delete it warms me that the deletion is irreversible so I hadn't tried that yet.

If it's been created by book metadata like comicinfo.xml, you would need to perform a "refresh metadata" on the books that were in the list.

**Comment by GiscardBiamby** [comment]
Thanks, it seems to work now. But for others who are using Mylar3 I'll note here that in order to get Mylar to include the StoryArcNumber inside the ComicInfo.xml, it seems you have to add the story arc to Mylar and then trigger a manual meta-tagging on all the issues of the StoryArc. 

Mylar automatically populates the "StoryArc" field in ComicInfo.xml for all comics, but it only populates the StoryArcNumber if you have explicitly added that story arc to Mylar. This results in Komga having a bunch of story arcs that have the wrong order, but the issue actually seems to be caused by Mylar. Manually adding all StoryArcs to Mylar would take a long time so I might try to write a python script to populate StoryArcNumber for all issues.

**Comment by evilhero** [comment]
I can speak on this, so hopefully @gotson doesn't mind.

Mylar uses its own internal reading order sequence - CV doesn't actually have a listed reading order sequence as its based solely on how the data is returned from CV. By default, mylar will order the data based on store date.

If you have it sorted by date you'll get a different order than if you sort it by publisher. And even date isn't actually the store date in most cases. Also, you will could also have TPBs mixed in with the arcs on CV, which means you'll have duplication, out of order numbering or even issues that don't even pertain to the given arc. 

So yeah, if you want the number populated then you need to have the arc within Mylar. This in linw with the fact that Mylar will be doing away with the not present CV reading order, and in its place be using an actual verified reading order from actual confirmed story arc orders (not implemented as of yet obviously).

**Comment by GiscardBiamby** [comment]
@evilhero does CV not provide reading order? If so, where is Mylar currently getting it from when you add an arc to Mylar?

**Comment by evilhero** [comment]
@GiscardBiamby I just explained it above - CV does not provide any reading order or sequence within their API to denote specific positions. It is based solely on how the query is to CV - if your query has a sort order by publisher, that's how it's returned. If it's by CoverDate, that's how it's returned. Ascending or Descending? Changes it again.

Mylar creates it's own reading order based on how it's initially retrieved from CV (which is by Store Date, not Cover Date). The problem is that when more than one issue has the same Store Date (ie, released in the same week), the actual reading order number can differentiate as then CV can actually send different results from the same query - which completely mucks things up. So while it's far from perfect, Mylar tries to keep the initial reading order sequence when adding or refreshing an existing arc. There are some options within Mylar (like being able to reorder the sequence manually), but they're also not 100% accurate because if the data retrieved from CV changes, then that alters things.

Eventually I'm looking to replace CV with comicbookreadingorders as a more accurate source of story arcs.
