### ISSUE TITLE
[Feature Request] Ignore definite and indefinite articles when sorting series

### ISSUE THREAD

**Issue by jonaballen** [gotson/komga#687]
### Is your feature request related to a problem? Please describe.
Series are sorted after [sort title], which groups a lot of titles under leading "A..." and "The..." 

Expected/preferred: "The Boys" should be filed under 'B' for "Boys" but would still display as "The Boys".
I believe this is the standard sort for items such as books, magazines or other reading artefacts.

### Describe the solution you'd like
Cut and move the definite and indefinite articles to the end of the title string when scanning library to set Sort tile for series to something like:

"The Boys" will be "Boys, The"or alternatively to just "Boys"

**Comment by gotson** [comment]
Very difficult to do when any language could be used for metadata. Do it by yourself, the sort title is there for that.

**Comment by jonaballen** [comment]
True, was thinking in English ^,

**Comment by Cirsten** [comment]
I know this closed, not even sure if this will be seen...

I know I can do it myself, but at a quick glance I have about 200 with "The" at the start which would take quite some time and effort to do so.

Rather than being an automated process there could be a user defined setting where I pick the words(s) to be excluded from the start of the shirt title
