### ISSUE TITLE
Integration with manga-py, gallery-dl [request]

### ISSUE THREAD

**Issue by phanirithvij** [gotson/komga#7]
### [manga-py](https://github.com/manga-py/manga-py)

+ There is a manga downloader `manga-py` which supports downloading manga from [a lot of websites](https://manga-py.yuru-yuri.sttv.me/#resources-list).
+ It can download each chapter as zip or cbz formats.
+ Also provides a Dockerfile.
### [gallery-dl](https://github.com/mikf/gallery-dl/)

+ This is a similar but a more popular one.
+ It supports many [`sites`](https://github.com/mikf/gallery-dl/blob/master/docs/supportedsites.rst) like `Instagram`, `DeviantArt`, `Pinterest` etc.

---
Request:
+ I think these go very well with komga.
+ It would be nice if Readme has some examples on how to use them with komga.

**Comment by phanirithvij** [comment]
And I also wanted to request one more feature.

> Is it possible to use a Tachiyomi extension as a server to serve all the downloaded manga in the android mobile?
i.e. the pc will become a client now

If yes I'd love to use it.

And also a download option on the client side i.e. the pc.

**Comment by gotson** [comment]
The [vision ](https://github.com/gotson/komga#status--vision)for Komga is to behave more like Plex, but for comics and mangas.

With Plex if you want to download some content, you can use other projects like Sonarr, Radarr, or Lidarr.

I have no plans at the moment to add any download capabilities to Komga, but since the projects exist you could use them to download what you want and move it to your library folder for Komga to index.

Regarding your second feature request i am not too sure to understand the use case, and anyhow it seems more related to Tachiyomi than to Komga.

**Comment by ArjixGamer** [comment]
> The [vision ](https://github.com/gotson/komga#status--vision)for Komga is to behave more like Plex, but for comics and mangas.
> 
> With Plex if you want to download some content, you can use other projects like Sonarr, Radarr, or Lidarr.
> 
> I have no plans at the moment to add any download capabilities to Komga, but since the projects exist you could use them to download what you want and move it to your library folder for Komga to index.
> 
> Regarding your second feature request i am not too sure to understand the use case, and anyhow it seems more related to Tachiyomi than to Komga.

i think he meant to downlaod manga with tachiyomi directly to his computer and use the komga extension to read them.

**Comment by gotson** [comment]
Please refrain from commenting on closed issues.
