### ISSUE TITLE
[Feature Request] Web clickable tag from Comicinfo in Komga book overview

### ISSUE THREAD

**Issue by sonostrass** [gotson/komga#750]
Hi Gotson,

Not any issue about that, just a useful feature...

Any chance to get access to **Web** tag from Comicinfo.xml in Komga web Interface at book level?
As a direct link bottom of book description? It's even better if it opens in a new window...

(A button nearby read/download ones would have been more nice-looking, but I guess, for security concerns, that it's better to see the real URL you're pointing at...)

Thanks again for your wonderful work!

sOnO

**Comment by gotson** [comment]
Hi, I didn't know what this field was for. I suppose it should contain a url? What's does it usually points to exactly? Are there any existing applications that would fill the Web element?

Komga doesn't have anything in its metadata model to represent external links for the moment though, so there's no place to import the data to.

**Comment by sonostrass** [comment]
Hi,

Thanks for considering this enhancement.
Here a short example: while parsing metadata with Bedetheque or ComicVine, the WEB tag point to its original parsing source.

```
<ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Title>Terre D'Élection</Title>
  <Series>A.D Grand-Rivière</Series>
  <Number>01</Number>
  <Summary>Grand-Rivière, c'est son nom. A.D. deux initiales et rien de plus. Personne n'a jamais réussi à en connaître la signification exacte.
Profession : commissaire principal, sept ans de métier.
Signe particulier : de couleur noire. Look rappeur, mais plutôt frappeur. Bonnet rasta, vieil imper, flingue en poche et carte tricolore de la police. La panoplie d'un flic pas comme les autres qui combat le fléau des cités.

Edition Info: N°33237</Summary>
  <Notes>Bedetheque.com - Wednesday 01 November 2017 17:04:36
BD2 scraper v4.8</Notes>
  <Year>2000</Year>
  <Month>1</Month>
  <Writer>Laurent-Frédéric Bollée</Writer>
  <Penciller>Al Coutelis</Penciller>
  <Colorist>Philippe Aymond</Colorist>
  <Publisher>Casterman</Publisher>
  <Genre>Polar, Thriller</Genre>
  <Web>https://www.bedetheque.com/BD-AD-Grand-Riviere-Tome-1-Terre-d-election-12596.html</Web>
  <PageCount>50</PageCount>
  <LanguageISO>fr</LanguageISO>

```

**Comment by gotson** [comment]
> while parsing metadata with Bedetheque or ComicVine

what app is doing that parsing ? is that a home made script, or a well-known ComicRack script?

**Comment by sonostrass** [comment]
Errr... please ask my lawyer. ^^

```
  <Notes>Bedetheque.com - Wednesday 01 November 2017 17:04:36
BD2 scraper v4.8</Notes>
```

**Comment by gotson** [comment]
Thanks, that's insightful.

**Comment by Kussie** [comment]
DoujinDownloader also fills in the Web tag with a link to the original source.

**Comment by gotson** [comment]
I am working on this, but i am not sure what's the best way to show the links in the UI.

To give you a bit of context, i don't want to limit the links to a single item. A book could have multiple links, and each link also need to have a label. You could have multiple links, for example for various websites (Bedetheque, ComicVine, Wikipedia…).

Here is some very crude rendering i just did:

<img width="940" alt="Screenshot 2021-12-28 at 17 07 27" src="https://user-images.githubusercontent.com/2139133/147549433-d18f720b-2264-46c4-ae40-f9ababab5296.png">

I am not sure we need to display the actual link target. Showing the link label with some visual hint that it's a link should be enough IMHO. The link targets do not bring much value in being displayed, since the link would have a label anyway.

I'm thinking of something like what Sonarr or Radarr are doing:
<img width="397" alt="Screenshot 2021-12-28 at 17 12 06" src="https://user-images.githubusercontent.com/2139133/147549895-9c667bd7-83e5-4e0a-9fc0-7b96beca9318.png">


The problem is that it's not very mobile friendly, as it needs hover to display.

Feedback welcome.

**Comment by sonostrass** [comment]
Hi,

My 2 pences about this:

- I agree that hoover display is a pain, especially for tablet/surface user like me
- I never get more than one web link for my use cases, but I suppose it's possible
- I suppose you parse the URL to get the domain as a link category, right? However, I feel it more secure to clearly see at minimum the link domain we're pointing at... because, after retrieving a book already containing web link from "unsecure places" (*cought cought*), I might point to an harmful target, isn't it?

Regards

**Comment by gotson** [comment]
> * I suppose you parse the URL to get the domain as a link category, right?

There's 2 different things:
- the data model, in which a weblink will have a label and a URL
- the parsing of the `Web` element from `ComicInfo.xml`, which doesn't have a label, so i use the URL host as a label. That's what you see in the above screenshot.

Here is a new mockup:
<img width="936" alt="Screenshot 2021-12-28 at 18 26 31" src="https://user-images.githubusercontent.com/2139133/147556997-1b55b582-5587-48bf-b1c6-68d6a037d1a9.png">



> * However, I feel it more secure to clearly see at minimum the link domain we're pointing at

That's exactly what you will get with links from a `ComicInfo.xml`.

**Comment by sonostrass** [comment]
Yup! Looks perfect to me!

Congrats!
