### ISSUE TITLE
Add continuous vertical reading mode (Webtoons)

### ISSUE THREAD

**Issue by MEGAMENE** [gotson/komga#81]
I don't know of feasible this feature would be, but I think an option to read vertical comics, like webtoons, would be a nice addition.
Preferably it would have smooth scrolling, but that might be hard with the current reader.

**Comment by gotson** [comment]
I thought about that already, I think we need two different vertical modes, a normal one that goes page by page, and a continuous webtoon one.

The page by page should be easy as the carousel component can be set as vertical. 

For webtoon, I should have a separate implementation with some kind of infinite scroll, but I'm not sure about the performances once the page has loaded lots of images. To be tested I guess.

**Comment by farahnur42** [comment]
Any ETA or update on this? I'd love to see it implemented because Komga more or less suffices my other requirements, but not having a continuous vertical mode of any sort is a deal-breaker for me. [Not sure if I should tack it on here or make a new comment/issue but adjustable zoom levels in the web reader and *maybe* AniList tracking/metadata would also be appreciated]

**Comment by gotson** [comment]
I cannot give any ETA, nor any prioritization between features. This is an open-source and free project on which I work on my free time. 

Please also refrain from asking or mentioning whatever other features you are interested in so as to keep github issues clean, concise, and on topic.
