### ISSUE TITLE
Komga doesn't set Age Rating from ComicInfo.xml's AgeRating tab after updating xml file

### ISSUE THREAD

**Issue by Majawat** [gotson/komga#885]
### Steps to reproduce

1. Have an existing comic in Komga with a ComicInfo.xml file in each cbz with no AgeRating tag
2. Update each ComicInfo.xml with an AgeRating xml tag (example: `<AgeRating>15+</AgeRating>`) (Mylar updated)
4. Have Komga Analyze and Refresh Metadata

### Expected behavior

Komga should set the Age Rating field to the AgeRating found in the newly updated AgeRating xml tag

### Actual behavior

No Age Ratting is set in the Komga series' field

### Komga version

v0.154.1-master

### Operating system

Docker running on unRAID

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
Provide debug logs.

**Comment by gotson** [comment]
> 2\. Update each ComicInfo.xml with an AgeRating xml tag (example: `<AgeRating>15+</AgeRating>`) (Mylar updated)

This is not a valid value, see https://github.com/anansi-project/comicinfo/blob/main/schema/v2.0/ComicInfo.xsd

**Comment by skyzuma** [comment]
i tested today with "Teen" AgeRating Tag but its not updated ...

**Comment by Majawat** [comment]
So if I'm reading this right, it has to be one of these values:

- Unknown
- Adults Only 18+
- Early Childhood
- Everyone
- Everyone 10+
- G
- Kids to Adults
- M
- MA15+
- Mature 17+
- PG
- R18+
- Rating Pending
- Teen
- X18+

That stinks, as Mylar does so by these values:

- All Ages
- 9+
- 12+
- 15+
- 17+
- Adult

Which I would prefer, given the simplicity, but I absolutely understand conforming to the established schema.

I'll create a feature request over at Mylar to conform with the ComicInfo schema. But (_if and only if_) Mylar decides not to, any chance of converting those values into Komga supported values?

**Comment by skyzuma** [comment]
if found the "problem" ... komga cant check / update replaced files ... i need to delete the files first (server and DB) and after an rescan ... the informations are there like "Teen" ... "MA15+" ...

**Comment by gotson** [comment]
> i found the "problem" ... komga cant check / update replaced files ... i need to delete the files first (server and DB) and after an rescan ... the informations are there like "Teen" ... "MA15+" ...

Probably a problem on your end. A scan in Komga should find the files have changed, and trigger a new analysis and metadata refresh.

**Comment by skyzuma** [comment]
u close this and u think thats fine? the problem is still there ...  but u dont have any interests on this, no problem ...

**Comment by gotson** [comment]
> u close this and u think thats fine? the problem is still there ... but u dont have any interests on this, no problem ...

I close it because the root cause is identified and not at komga level as you mentioned it's mylar not setting the right value.

Your other problem of not picking up files is not the same problem, so either ask on Discord or open a new issue.

And drop the attitude right away, this is a free project with free support. You're not happy? Go somewhere else.

**Comment by gotson** [comment]
> u close this and u think thats fine? the problem is still there ... but u dont have any interests on this, no problem ...

And not mentioning that you piggy backed someone else's issue, but with different symptoms..

@Majawat did the right thing, he opened an issue at mylar level, and that is what was needed. 🙏🏻 

You @skyzuma you just added random comments on an opened issue that you thought would be similar to what you experience, and then complain when the actual issue of the op is marked as closed, because you have something unrelated still going on.

Honestly, we don't need people like you around here.
