### ISSUE TITLE
Pagination on series/book grids

### ISSUE THREAD

**Issue by gotson** [gotson/komga#91]
Browsers will hang if too many series or books are shown on screen (1000+). Adding paginated navigation instead of showing everything would help.

Pagination should be a choice of display if the number of item is under a threshold.

Should help address #86.

**Comment by Gyokusai** [comment]
I'm encountering this issue as well. I don't think it's even about the server strength, I have a decent E5-2690 unraid server and my browser hangs whenever I try to load my library, I don't see any resources being throttled as well.

The biggest giveaway that pagination would fix this issue is that interestingly, the Tachiyomi extension has no issues at all browsing the site (since tachiyomi has built in pagination).

**Comment by gotson** [comment]
Tachiyomi and the webui are 2 totally different things:
- Tachiyomi is a native Android app. Android has powerful UI components that handle a very high number of items.
- The webui is a website built with VueJS and Vuetify, running in a web browser. A webpage with a massive amount of items will often bring the browser to a grind.

**Comment by Gyokusai** [comment]
Thanks for the explanation. Hopefully pagination does fix it on the browser though, I really love to use Komga for my library.
