### ISSUE TITLE
[Feature Request] possible to have public libraries

### ISSUE THREAD

**Issue by albjeremias** [gotson/komga#95]
### Is your feature request related to a problem? Please describe.
I'd like that it is possible for a user to visit public libraries, without any login.. only allowed to view/download no to upload, then it should request an account, via other way... (other feature: or registering and waiting for approval)

### Describe alternatives you've considered or other apps that can do what you want
I was expecting komga to do exactly this... 

### Help
How hard would it be to add a feature, where you could tick an option in a library to turn it public.. and if the komga server has a public library, then it would change its main page to a list of libraries, and a pre-selected library?

**Comment by gotson** [comment]
What would be the use case for public libraries? What's the intended population?

**Comment by albjeremias** [comment]
it's a public zine library for anarchist zines.. they are in pdf and most of them have no copyright issues... :)

**Comment by gotson** [comment]
What about the intended population? Would it be everyone possibly on the internet?

How is the distribution of those zines done at the moment, and what's the limitation with the current distribution model?

**Comment by albjeremias** [comment]
Now they are in a usb stick, in a infoshop in Lisbon... :) the limitation, is that peepz in other places have problems to get them.. we could send by post.. but we want to add a library to our project.. we are already hosting peertube, mastodon and others.. so a zine/library makes sense to us!

**Comment by gotson** [comment]
If it's just a matter of distribution any file server could fit the need.

I understand the need, I'm not sure it's shared by many though. 

On the technical side of things that would mean reviewing the security model of the whole api to authorize unauthenticated access, with a finer grain access control at endpoint level. Teh finer part is doable since something similar is already in place for libraries, series and books with limited access. Unprotecting all the endpoints by default would require a bit more work to add security everywhere when needed though. 

That's not a small task.

**Comment by albjeremias** [comment]
hm ok.. i'll search for something else... nice stuff anywayz :)

**Comment by albjeremias** [comment]
hmm, couldn't we just create an "anonymous" acct? with a button: "login as anonymous?" ?

**Comment by gotson** [comment]
> hmm, couldn't we just create an "anonymous" acct? with a button: "login as anonymous?" ?

That wouldn't work, as accounts are tied to an email address, and the account stores data related to the user like preferences, read progress etc.
